= 2. 팀워크 이끌어내기

소프트웨어 엔지니어링의 문화적/사회적 측면

소프트웨어 개발은 '팀의 단합된 노력' 의 결실이다

== 코드를 숨기고 싶다

불안감. 진행 중인 작업물을 다른 사람이 보고 판단하는 걸 두려워한다

비난받고 싶지 않음

== 천재 신화

팀이 이룬 성공을 단 한 사람에게 몰아주어 만들어지는 경향

천재 환상

* 새로운 개념이 떠오름 -> 완벽하게 구현 -> 공개하여 천재성에 충격을 받게 -> 동료들이 놀람 -> 사람들이 몰려듬 -> 명성과 부

사회성이 부족한 사람은 팀원으로 적합하지 않다

많은 사람이 자신의 실수를 보면 자신이 천재가 아님을 눈치챌 것이라는 두려움 때문에 프로젝트를 공유하길 꺼린다 +
코드가 완벽해질 때까지 숨긴다

== 숨기는 건 해롭다

위험성을 키우고 성장 잠재력을 속이는 것

=== 조기 감지

초기 설계에는 실수가 있기 쉽다. 바퀴를 다시 발명할 수도

피드백을 조기에 받을 수록 위험이 크게 들어든다 - 일찍, 빨리, 자주 실패

=== 버스 지수

몇 명의 팀원이 버스에 치어서 일을 할 수 없게 될 때 프로젝트가 망하게 되는지

책임 영역마다 2차 소유자를 두고 문서를 갖추면, 프로젝트의 미래를 보장하고 버스 지수를 높이는데 도움이 된다

많은 정보로 다른 이들이 직접 체득한 경험을 대체할 수는 없다

=== 진척 속도

코드의 품질을 높게 유지, 소프트웨어가 조금씩 올바른 방향으로 나아가게 한다 +
DevOps - 가능한 일찍 피드백/테스트, 보안과 프로덕션 환경을 가능한 한 초기부터 고려한다

전체 프로젝트 수준에서도 빠른 피드백 루프가 돌아야 한다 +
눈이 많아야 프로젝트가 탈선하지 않고 옳은 방향으로 나아간다 (Many eyes make sure your project stays relevant and on track)

(사례 연구 - 여기랑 반대로 티맥스는 채용 설명회 왔을 때 1인 1사무실이라고 자랑했던..)

=== 결론, 숨기지 말자

== 모든 건 팀에 달렸다

소프트웨어 엔지니어링은 팀의 단합된 노력이다

=== 사회적 상호작용의 세 기둥

. 겸손 (humility)
. 존중 (respect)
. 신뢰 (trust)

=== 세 기둥이 중요한 이유

일이 진행되도록 관계를 형성하라 +
내가 필요할 때 동료들이 기꺼이 수고해줄 수 있음

=== 겸손, 존중, 신뢰 실천하기

* 자존심 버리기
* 비평하고 비평받는 법 배우기
** 잘못했다, 고치라, 다른 사람들과 다르게 했다, 고 비난하면 안되다
** 상대가 틀린게 아니라 내가 코드를 이해하는 데 문제를 겪는 것으로 보이게
* 빠르게 실패하고 반복하기

=== 비난 없는 포스트모템 (postmortem) 문화

실패한 근본 원인을 분석하여 문서로 남기는 것이 실수로부터 배우는 핵심

무엇을 배웠는지, 배운 것을 토대로 앞으로 무엇을 바꿀지가 담겨야 +
쉽게 열람할 수 있고 제안한 변화를 팀이 실천하는지 확인

* 사건의 개요
* 인지하고 해결에 이르기까지 타임라인
* 사건의 근본 원인
* 영향과 피해 평가
* 문제를 즉시 해결하기 위한 조지 항목 (소유자 명시)
* 재발 방지를 위한 조치 항목
* 해당 경험에서 ㅓ얻은 교훈

인내심을 기르기, 마음을 열고 받아들이기 (다른 사람이 내 생각을 바꿔도 괜찮다)

=== 구글답게 하기

Googleyness - 구글다움이 갖춰야할 기준 정의. '겸손, 존중, 신뢰' 를 드러내는 태도와 행동들을 정의 +
구글답게라는 용어는 사용하지 않게 되었다

* 모호함을 뚫고 번창한다
* 피드백을 소중히 한다
* 저항(항상성)을 극복한다
* 사용자를 우선한다
* 팀에 관심을 기울인다
* 옳은 일을 한다