= 3. 지식 공유

조직 내에는 질문의 답을 아는 전문가 & 전파할 메커니즘 필요 +
배움의 문화가 자리 잡혀야 한다 & 모르는 걸 인정할 수 있도록 돕는 심리적 안전을 제공해야 한다

== 배움을 가로막는 장애물

* 심리적 안전 부족 - 불이익이 두려워서
* 정보 섬 - 조직 간 소통하거나 자원을 공유하지 않아 지식이 파편화
** 정보 파편화, 정보 중복, 정보 왜곡
* 단일 장애점 (SPOF)
* all-or-nothing expertise
** 새로운 전문가를 키우기 위한 멘토링이나 문서화에 신경 쓸 여력이 준다
* 앵무새처럼 흉내내기 (parroting)
* 유령의 묘지 - 잘못이 두려워서 아무도 손대지 않는 영역

== 철학

문서화된 지식은 팀을 넘어 조직 전체로 퍼뜨릴 수 있다 +
문서는 더 일반적인 상황이므로, 특수 상황에서는 적합하지 않을 수도 & 최신 정보 유지보수 비용

기록된 지식은 확장성이 좋지만, 사람이 해주는건 다양한 지식을 종합할 수 있는 장점

현장 지식과 문서화된 지식은 서로를 보완해준다

조직 스스로 교육하고, 배우고 성장하는 데 집중하고, 충분한 수의 전문가를 양성해야 한다

== 판 깔아주기: 심리적 안전

이해하지 못한게 있음을 인정, 무지를 탓하지 말고 솔직함을 반겨야 한다 +
'무언가를 시도하다가 실패해도 안전하다' 는 인식

=== 멘토 제도

궁금한 점에 답해주고 신규 입사자의 성장을 돕는 것 +
팀의 팀원, 관리자, 테크 리드는 멘토에서 제외 - 시간을 뺏는다는 걱정 없이 마음 편히 물어본다

구글에서는 +
1년 이상 근무했고, 인프라부터 문화에 이르기까지 무엇이든 조언해줄 수 있는 사람

=== 큰 그룹에서의 심리적 안전

그룹의 모든 구성원이 안전한 환경을 만들고 유지하는 역할을 함께 해줘야 +
협조적으로 일하는 문화

[cols="1,1,1"]
|===
|공통 문장 |협조적 |적대적
|기초적인 질문과 실수를 |올바른 방향으로 안내 |가려내서 질문한 사람을 꾸짖음
| |질문자가 배우게끔 도와줄 목적으로 설명 |자신의 지식을 뽐낼 목적으로 설명
| |상냥, 인내심을 갖고 도움이 되게 대응 |잘난체, 비난, 건설적이지 못한 방식으로 대응
| |해법을 찾기 위한 공개 토론 형식으로 상호작용 |승자, 패자를 가리는 논쟁 형식으로 상호작용
|===

사회적 규칙

* 거짓된 놀람 금지 - 모른다는 사실을 인정하기 두려워하게 된다
* 음, 실제로는.. 금지 - 세세하게 고쳐주는 행위 = 자신을 뽐내려는 무의식
* 뒷좌석 운전 금지 - 적절한 발언권 없이 끼어들어 의견 제시 금지
* 미묘한 ~주의 금지 - 인종, 연령 등 다른 이에게 불편함과 무례함, 불안함

== 내 지식 키우기

항상 무언가 배울 게 있음을 인식

=== 질문하기

질문하는걸 두려워하지 말고, 모르는 분야가 나오면 두려워하지 말고 성장하는 기회로 받아들여라

항상 무언가 배울 게 있는 환경에서 살아야 한다. 그렇지 않으면 더 이상 성장하지 못한다 (새로운 환경을 찾아 떠나게 될 것)

조직의 리더들이 솔선수범해서 이런 문화를 만들어야 한다 +
'상급자라면 모든 걸 알아야 한다'는 인식이 생겨나지 않도록 주의

끈기를 가지고 상냥하게 답변해줘야 안심하고 도움을 청하는 환경이 조성된다

=== 맥락 이해하기

기존 설계와 구현을 뒷받침하는 결정 사항들을 더 깊이 이해하는 일도 배움에 포함

'무언가를 옮기거나 바꾸려면 그게 왜 그 자리에 있는지부터 이해하자'

정상이 아니라고 보이는 결정에 대해서는 먼저 맥락을 이해해야 한다 +
코드의 목적과 맥락 파악 -> 변경하려는 방향이 여전히 더 나은지 고민

== 질문 확장하기: 커뮤니티에 묻기

무언가를 배울 때 기록하는 습관, 나중에 기록해둔 지식을 공유

=== 그룹 채팅

동시에 여러 사람에게 질문 던지기 +
주제나 팀별로 개설되는 경향

간단한 질문에 적합 +
정보를 외부에 공유해야 하거나 참조할 일이 있으면 문서 or 메일링 리스트'

=== 메일링 리스트

그룹 채팅에 질문하는 것과 비슷하지만 더 많은 사람과 공유하기 쉽다 +
검색 가능한 아카이브, 메일 스레드

맥락 정보가 많이 필요한 복잡한 질문에 적합, 빠르게 주고 받는 대화에는 취약 +
내용을 수정할 수 없어 최신성 보장이 안됨

=== YAQS: 질의응답 플랫폼

== 지식 확장하기: 누구나 가르칠 게 있다

=== 오피스 아워

누군가가 특정 주제에 관한 질문에 답해줄 목적으로 시간을 비워 둔 정기적인 이벤트 +
(비효율 때문에 거의 활용하지 않음)

전문가와 직접 대면할 기회 제공 +
문제가 불명확하여 어떻게 질문해야 할지 모를 때 or 문서화되지 않은 특수한 문제에 맞닥뜨렸을 때

=== 기술 강연 (tech talk) 과 수업 (class)

engEDU (Engineering Education), g2g (Googler2Googler)

기술 강연 - 연사가 청중에게 직접 강의하는 형태로 진행 +
수업 - 강의도 있지만 실습이 있는 경우가 많아 참석자들이 더 적극적으롳 참여해야 한다 (비용이 많이 들어 가장 중요하거나 어려운 주제)

수업의 효과를 극대화하는 조건

* 자주 오해를 일으킬 정도로 복잡한 주제
* 비교적 안정적인 주제 - 내용이 자주 바뀐다면 다른 공유 형태
* 질문에 답해줄 교사가 있어야 효과가 큰 주제
* 정기적으로 개설해도 될 만큼 수요가 많아야

=== 문서자료

무언가를 배우도록 돕는 기록된 지식

새로운 문서자료를 작성하거나 기존 문서자료를 기여할 기회 포착

* 문서 자료 갱신하기 - 막 배운 순간
** Getting Started, 실수/빠진 부분
* 새로운 문서자료 작성하기
** 새로운 개발 흐름을 만들어냈다면, 단계를 설명하는 문서자료 작성
** 피드백 - 버그 리포트 제줄, 댓글 작성 등
* 문서화 촉진하기
** 문서자료에 담긴 정보 - 기본으로 참고해야 하 ㄹ표준
** 팀 외부로 확산

=== 코드

코드 문서화 - 라이브러리를 이용자 & 유지보수하는 사람들에게도 큰 혜택 +
주석은 지식을 미래로 전달

== 조직의 지식 확장하기

=== 지식 공유 문화 일구기

==== 존중

지식을 공유할 때는 상냥함과 존중을 담아야 한다

[quote]
리더는 주변 사람들을 성장시키고, 팀의 심리적 안전을 개선하고, 팀워크와 협업 문화를 조성하고, 팀 내 긴장을 해소하고, 구글 문화의 가치를 설정하며, 구글을 더 활기차고 신나는 일터로 가꿔야 합니다

==== 보상과 인정

조직에서 어떤 가치를 추구할지 정하면, 그 가치를 강화하는 일에 적극적으로 보상해야 한다

칭찬보다는 확실한 보상에서 동기를 얻는다

높이 올라설수록 영향력이 중요해짐, 더 많이 요구

* 주니어 직원들의 멘토 - 기술적 성장 & 미래의 리더로 육성
* 코딩, 설계 리뷰, 엔지니어링 교육과 개발, 전문 분야와 관련하여 여러 활동을 통해 구글의 소프트웨어 커뮤니티를 지탱하고 발전시킴

동료 상여, 쿠도스 - 동료를 인정해준다

=== 표준 정보 소스 구축하기

회사 차원의 중앙집중적 정보 원천, 전문가의 지식을 표준화하고 전파하는 수단

조직 차원에서 합의한 내용을 제공, 해당 분야 전문가들이 적극적으로 관리하고 감독해야 한다 +
복잡한 주제일수록 소유자를 명확히 해야

==== 개발자 강드

코딩 스타일 가이드, 공식 소프트웨어 엔지니어링 모범 사례, 코드 리뷰 가이드, 테스트 가이드, 금주의 팁 (TotW)

==== go/ 링크

구글 내에서 쓰는 URL 단축 서비스 +
go/python - 구글의 파이썬 개발자 가이드

* 아주 짧아서 공유가 쉽다
* 실제 URL 이 바뀌어도 go/ 링크는 바뀌지 않음 - 옮길 때 대상 URL 만 변경

==== 코드랩

엔지니어에게 새로운 개념이나 프로세스를 가르치는 실습현 튜토리얼

==== 정적 분석

검사 로직을 자동화할 수 있는 모범 사례들을 공유하는 강력한 수단

=== 소외되지 않기

==== 뉴스레터

업무에 꼭 필요하지는 않지만 엔지니어들이 관심을 가질만한 정보를 유통하는 괜찮은 수단

==== 커뮤니티

== 가독성 제도 (readability): 코드 리뷰를 통한 표준 멘토 제도

프로그래밍 언어 모범 사례를 전파하기 위한 구글 전사 차원의 '표준 멘토링 프로세스'

모범 사례를 가르치고, 어떤 공유 인프라를 활용할 수 있으며, 구글에서의 코드 작성이란 어떤 것인지

=== 가독성 인증 프로세스란?

모든 changelist 는 가독성 승인을 얻어야 한다 +
해당 언어의 가독성 자걱증을 가진 누군가가 해당 CL 을 승인했다는 표시

언어별 가독성 자격증 - '특정 프로그래밍 언어를 사용하여 구글의 모범 사례와 코딩 스타일에 맞는 명확하고 관용적이고 유지보수하기 쉬운 코드를 일관되게 작성하는 사람' +
1~2%

중요한 멘토링 수단 + 협업 수단

표준화와 개인화가 융합된 방식의 지식 확장 수단

=== 가독성 인증 프로세스를 두는 이유

모든 엔지니어는 다른 팀의 코드에서 풍부한 지식을 얻음

문서로 정리된 모범 사례들 -> 코드가 따라야 할 일관된 표준 제공 +
가독성 제도는 이 표준들을 시행하고 전파하는 메커니즘

현장 지식 이상을 전달한다는 매우 큰 장점

단점으로는 비용이 저렴하지 않다

* 자격증이 없는 팀에는 부담 - 리뷰어를 팀 외부에서 찾아야
* 검토를 받아야 하는 작성자 - 리뷰를 한 차레 더
* 확장성이 떨어진다 - 인간 리뷰어에 의존하여 진행

들이는 비용에 비해 얻어지는 이익이 더 많은가

엔지니어링 속도에 긍정적인 영향을 준다 - CL 검토 시간이 훨신 짧음, 코드 품질에 대한 만족도가 높음