= 4. 공정 사회를 위한 엔지니어링

== 편견은 피할 수 없다

인력 구성 면에서 사용자들을 대표하지 못한다 = 제품이 대표성이 부족하거나 취약 계층 사용자들에 미치는 영향을 이해하기에 다양성이 부족하다

여러 제품들. 자동완성, 광고 시스템..

사용자의 신뢰가 무너지고 참여도가 낮아졌다

== 다양성이 필요한 이유 이해하기

모두를 위한 제품을 개발하려면 먼저 우리가 어떤 사람들을 대표하는지 이해해야 한다

팀 차원에서 다양한 계층을 대표할 수 없다면, 엔지니어 각각이 모두를 위한 제품을 만드는 방법을 배워야 한다

(한국계 미국인 배우가 인터뷰한게 떠오름 +
한국인은 그 자체에서 소수였던 적이 없다. 그래서 다양성을 이해하지 못하는 편이기도 하다)

== 다문화 역량 갖추기

제품이 어떻게 다른 그룹의 사람들에게 유/불리하게 작용하는지 이해하는 능력 +
무언가를 만들어야 할 때와 아닐 때를 구분하는 안목도 갖춰야 한다

인류 전체의 다양한 경험을 이해할 수 있는 역량 개발에도 힘써야 한다

== 다양성 실천하기

형평성과 공정성에 대한 정량화, 실행 가능한 일에는 무엇이 있는지 고민하는게 중요하다 +
(정량화를 어떻게..?)

후보자 중 여성 혹은 다른 소수자 포함? +
누군가를 고용 -> 어떤 성장 기회를 주고, 그 기회가 공평하게 돌아가는가? +
모든 TL 과 SE 관리자가 팀 내 공정성을 강화할 수단을 가지고 있는가? +
...

== 단일한 접근 방식 거부하기

직장에서의 대표성을 높이려면 단일한 접근 방식에서 탈피해야 한다

많이 쓰이는 기능을 먼저 만들고, 특수한 상황에 쓰이는 기능이나 개선은 나중에 미루는 방식으로 진행 +
-> 기술을 접하기에 유리한 사람들에게 우선권을 줘서 불평등하게 가중하는 방식 +
(이건 근데 비용이랑 엮이는 문제인 것 같은데..)

다양한 언어와 문화, 여러 계층에 걸친 사용자 그룹을 대상으로 사용자 경험을 연구해야 한다

== 가치 vs 결과

. 자신을 솔직하게 바라보고 성찰하기
. 모두를 위해 만들지 말자. 모두와 '함께' 만들자
. 제품을 이용하기 가장 어려운 이들을 위해 설계하자 (= 단기적인 속도를 위해 공정성을 포기하지 말자)
. 가정하지 말고, 시스템 전반의 공정성을 측정하자
. 변할 수 있다

== 관심을 잃지 말고 전진하자