= 5. 팀 이끌기

manager: 사람을 이끌고 +
tech lead: 기술과 관련한 책임

== 관리자와 테크 리드

=== Engineering Manager

엔지니어링을 아는 사람 만이 '엔지니어링 관리자'가 되게

팀 구성원 모두의 성과 (performance), 생산성 (productivity), 행복 (happiness) 을 책임져야 한다 +
팀에서 만드는 제품의 사업적 요구도 충족시켜야 한다

=== Tech Lead

제품의 기술적인 면, 기술과 관련한 결정과 선택, 아키텍처, 우선순위, 성능과 일반적은 프로젝트 관리

규모가 크면 Program manger 를 두어 프로젝트 관리를 지원하기도 한다

관리자와 함께 필요한 팀원을 확보 & 엔지니어들의 기술 스펙트럼과 기술 수준을 최대한 활용 -> 목표 완수

직접할지, 팀원에게 위임할지를 판단해야 한다

=== Tech Lead Manager

소규모 초기 팀

경력이 오래된 사람에게, 특히 최근까지 개인 기여자 (IC) 였던 사람에게 맡김

자신의 일, 위임, 사람 관리 사이에서 균현을 잡는 요령을 배워야한다

== 개인 기여자에서 리더로

누군가는 리더를 해야 제품이 어느 방향이든 나아갈 수 있다 +
원치 않아도 리더가 될 수 있다

=== 두려워해야 할 것은 전부다

'관리' 를 하면 오늘 한 일이 하나도 없다고 생각하는 경우가 많다. 수량화가 어렵기 때문 +
-> 활기를 불어넣고 생산성을 높일 수 있다

구글은 다음 직급으로 승진시키기 전, 현 수준 이상의 일을 일정 기간 맡겨본다

테크 리드나 관리자를 고려해볼만한 이유 +
-> 경력 스펙트럼을 확장하는 길 (혼자 작성할 수 있는 건 한계가 있다) +
-> 천부적인 관리자일수도 (사람들을 지도하고, 도와주고, 보호하고, 회사의 요구를 잘 채우는)

=== 섬기는 (Servant) 리더십

마이크로매니징, 저성과자 방치, 만만한 사람 고용 등의 안좋은 방식 +
'무엇보다도 관리하려는 충동을 이겨내야한다'

관료적인 장애물 치우기, 합의를 이르게 도와주기, 저녁을 사주기 등

== 엔지니어링 관리자

=== 전통적인 관려자

뾰족 머리 관리자 (pointy-haired manager) - 노동자를 잘 대우해주거나 작업 환경을 개선해줄 필요를 느끼지 못함 +
당근과 채찍은 비효율적, 창의적인 사람의 생산성을 떨어뜨림

=== 오늘날의 엔지니어링 관리자

팀이 나아갈 길을 다짐과 동시에 안전과 복지를 챙겨준다

[quote]
전통적인 관리자는 일을 '어떻게' 처리할지 고민, 훌륭한 관리자는 '무슨' 일을 처리할지 고민 (팀을 믿고 맡긴다)

실패한 개인에게는 개인적으로 따로 불러서 건설적인 비판을 해줘라

== 안티패턴

=== 만만한 사람 고용하기

컨트롤 가능한 사람을 고용해서 권위와 위치를 위협하지 못하게 +
직접 처리해야 할 일이 늘어난다

자신보다 똑똑하고 대체할 역량을 갖춘 사람을 적극적으로 뽑아야 한다 +
스스로 할 일을 찾고 확장, 일부는 스스로 팀을 이끌고 싶어할 것 +
자신의 전문성을 확장하는 데도 유리하다

=== 저성과자 방치하기

팀의 고성과자들은 저성과자들을 밀고 당겨주느라 에너지 낭비, 사기가 떨어져간다 +
새로운 고성과자가 팀에 합류하는 걸 막고, 있는 사람도 떠나게 된다

기간을 정하고 (두 달 정도?) 아주 구체적인 목표를 제시, 작고 점진적이고 측정할 수 있는 목표 +
매주 만나서 진척 상황 확인, 다음 마일스톤에서 기대하는 바를 명확히 정의했는지, 성공/실패를 바로 구분할 수 있는지 확인

저상과자와 직접 대면하여 중요하고 꼭 필요한 변화를 촉진

=== 사람 문제 무시하기

업무에 특별히 문제가 되는 경우가 아니라면, 공감해주기

=== 만인의 친구 되기

부드럽게 끌어주는 리딩과 우정을 혼동하지 마라

팀원들을 불편하게 하지 않으면서, 업무 외적인 대화를 나누며 사회적 유대 유지

=== 채용 기준 타협하기

A급 인재는 A급 인재를 뽑고, B급 인재는 C급 인재를 뽑는다

적절한 사람을 찾는데 드는 비용 < 애초에 뽑지 말았어야 할 직원을 관리하는 비용

=== 팀을 어린이처럼 대하기

마이크로매니징, 자신의 일에 책임질 기회를 주지 않는 경우

믿을만한 사람을 뽑고 신뢰를 보여준다면 능력을 발휘할 것

== 올바른 패턴

=== 자존심 버리기

팀이라는 '집단'으로써의 자존심과 정체성을 강화해야 한다 +
신뢰의 한 축 - 팀을 믿어라. 팀원들의 능력과 기존에 이른 성과들을 존중해야 한다

실무자가 더 세부사항을 잘 알고 있을 것이라고 확신 +
팀을 하나로 모으고 방향을 정하게 해주는 것은 관리자의 몫이지만, 구체적인 방법은 현장에서 결정하는게 훨씬 낫다는 뜻 +
팀원들의 주인의식과 책임감이 커지게 된다

질문 = 더 잘 이해하기 위한 노력 +
질문하기를 장려 -> 건설적인 비판이 이루어지는 더 나은 팀의 더 나은 리더가 될 가능성

실수했다면 사과하기

=== 마음 다스리기

더 많은 사람을 이끌수록 감정은 억누르고 평정심을 유지해야 한다 +
사람들은 어떻게 행동하고 반응해야 할지 단서를 윗사람에게서 얻는다

질문하기가 하나의 요령 +
조언을 청한 사람이 자기 힘으로 문제를 해결하도록 도와주려 노력해야 한다 +
= 문제를 다시 정의하고 탐구해보도록 보조해줘라. 질문자 스스로강 ㅣ끌어낸 그 사람의 답

=== 촉매자 되기

catalyst - 반응에 직접 참여하지 않지만 다른 물질의 화학반응을 가속하는 물질

서로를 가까이 끌어당겨주어 상호작용이 일어날 가능성이 커지게

합의를 이끌기

=== 장애물 치우기

장애물에 막혀있을 때 - 장애물을 치워줄 수 있고 그러길 원한다는 것을 팀원 모두가 인지하도록 만들어야 한다

정확한 답을 알고 있기보다 올바른 사람을 알고 있을 때의 가치가 더 크다

=== 선생이자 멘토 되기

스스로 배울 기회를 주는 일

성장하는 팀에 발맞춰 멘티가 배우는 데 쓰는 시간과 제품 개발에 기여하는 시간의 균현을 잘 잡아줘야 한다

멘토가 되는데 필요한 것

. 팀의 프로세스와 체계에 대한 경험
. 다른 이에게 무언가를 설명해주는 능력
. 멘티에게 도움이 얼마나 필요한지를 측정하는 능력

=== 명확한 목표 세우기

리더가 설정한 방향을 모든 팀원이 이해하고 동의

mission statement (사명) - 팀이 이루어야 할 임무를 구체적인 문장으로 적어놓는 것

자율권을 주고 올바르게 가고 있는지 주기적으로 확인 -> 다른 리더십 엄무에 신경 쓸 수 있고, 팀의 효율을 올린다

=== 정직하기

어려운 피드백을 전할 때 칭찬 샌드위치 방식으로 충격을 완화하는 것은 하지 마라 +

ex) 팀의 탄탄한 구성원이자 가장 영리한 엔지니어 -> 코드가 복잡하고 이해하기가 힘들다 -> 잠재력이 크니 좋은 티셔츠를 하나 주겠다

둘러진 것 때문에 핵심 메시지를 인지하지 못하는 경우가 많다

**직접적인 피드백이나 비판을 전할 때는 메시지를 정확하게 왜곡 없이 전달**

=== 행복한지 확인하기

팀의 생산성을 장기적으로 끌어 올리려면, 팀원들이 행복해하는지 확인

팀원들과 일대일 면담 마지막에 필요한게 없는지 묻기 -> 생산성과 행복 증진에 필요한 것을 갖춰주는데 좋은 멘트

== 예상하지 못한 질문

팀원이 모든걸 성취할 방법을 고민하고, 고민을 하고 있음을 팀원들이 알게 해야 한다

== 그외 조언과 요령

* 위임하되, 곤란한 일은 직접 처리
* 대신할 사람을 찾자
** 적합한 팀원을 구하면 팀을 이끌어볼 기회를 줘야 한다
* 파도를 일으켜야 할 타이밍을 알자
** 문제를 끌 수록 안 좋은 영향 -> 빠르게 조치를 취해야 한다
* 혼란으로부터 팀을 보호하자
** 조직 차원에서 벌어지는 무질서로부터 모르게, 보호하기
* 팀에 공중 엄호를 해주자
** 회사 위에서 무슨 일이 벌어지고 있는지 팀이 알게
* 팀이 잘하고 있다면 칭찬하자
* 실패해도 쉽게 되돌릴 수 있는 일에는 '해보세요'라고 말하자

== 사람은 식물과 같다

사람마다 다르다

방향지시, 수행해야 할 작업에 대한 기본적인 이해, 간단한 조직관리 기술, 전체 작업을 관리 가능한 단위로 쪼개는 능력

=== 내적 동기와 외적 동기

intrinsic, extrinsic

가장 행복하고 생산적이게 만드는 비법 - 내적 동기 +
자율성, 숙련, 목적 3가지로 동기부여

* 자율성 (autonomy)
** 마이크로매니징 없이 스스로 행동할 수 있는 것
** 제품과의 관계가 더 끈끈해지고 주인의식이 커진다
* 숙련 (mastery)
** 현재 기술 수준을 높이고 새로운 것을 배울 기회 제공
** 동기가 커져 더 강한 팀을 만들어 준다
* 목적 (purpose)
** 노력에서 의미를 찾고 분명하게 인식시켜주어야 한다
** 제품을 더 나은 방향으로 개선할 영감을 주는 조치