= 6. 성장하는 조직 이끌기

깊게 보다는 넓게 살펴야 하는 위치 +
엔지니어들을 올바른 방향으로 이끄는 능력이 중요해진다

3A 리더십 - Always be deciding, Always be leaving, Always be scaling

== 늘 결정하라 (Always be deciding)

눈가리개를 찾고 -> 트레이드오프를 파악 -> 해법을 결정하고 반복

=== 눈가리개 찾기

나에겐 처음이지만 다수에겐 계속 문제였던 것을 찾아서

질문, 새로운 전략 모색

=== 핵심 트레이드오프 파악하기

옳은 답은 없으며 특정 상황에서의 최선의 답

모든 트레이드오프를 보여주고 설명한 다음 어떻게 균형을 맞출지 결정하도록 도와야 한다

=== 결정하고 반복하기

트레이드오프들의 존재를 알고 작용하는지 이해하면 힘이 커진다 - 최선의 결정을 내릴 수 있음

트레이드오프의 지속적인 재조성을 하지 않으면, 완벽한 해법을 찾으려고 하여 분석 마비에 놓이기 쉽다

우선 결정대로 실행 -> 지켜보기 -> 유지하거나 취소하고 다른 결정을 내리거나

== 늘 떠나라 (Always be leaving)

스스로 문제를 풀 수 있게 유도해야 한다. SPOF 가 되면 안된다

=== 자율주행 팀을 만들기

사람들을 조직하여 자생력을 갖춘 조직으로 만들기

문제 공간 분할 -> 하위 문제 위임 -> 필요에 따라 반복

=== 문제 공간 분할하기

보통은 팀에 하위 문제 하나씩 배정하게 되는데 +
하위 문제들은 시간이 지나면 변할 수 있지만, 팀은 경직된 경계에 갇혀 변화를 눈치채기 어려움

가능하다면 조직의 구조를 느슨하게 관리 +
팀 규모를 유동적으로, 다른 하위 팀으로 옮길 수 있게, 상황이 변하면 할당된 문제를 바꿀 수 있게

==== 하위 문제를 다른 리더에게 위임하기

자생력을 갖춘 리더들을 키우는 가장 효과적인 방법 - 위임 +
과제를 주고 실패 -> 도전을 반복하도록

시급만 문제가 아니라면 맡겨라 +
성장할 기회를 마련해주어 업무 크리티컬 패스 상에서 빠질 수 있도록

'우리 팀원 중 아무도 할 수 없는 것 중 내가 할 수 있는 것은 무엇일까?' 라는 질문을 던져보라 +
조직 정치, 고차원적인 전략 정의, 장기적인 청사진 그리기 등

==== 조율하고 반복하기

관찰과 경청 95%, 절묘하고 시의적절한 개입 5% 가 좋은 관리이다

==== 팀 정체성 설정 시 주의점

'문제'를 맡겨야 한다. '제품'이 아니라

제품은 문제에 대한 해결책, 제품은 더 나은 제품으로 바뀔 수 있다

제품이 팀의 정체성이 되고 가치와 동일시되어 눈을 가려버리는 문제가 될 수 있다

== 늘 확장하라 (Always be scaling)

팀 규모 확장을 방어적인, 개인적인 입장에서 +
자신의 제한된 시간, 집중력 에너지를 보호하면서 책임과 영향력을 키우는

=== 성공 사이클

분석 -> 분투 -> 견인 -> 보상(압축)

새로운 문제를 받아왔는데 인력 충원은 없음 +
원래의 문제도 관리가 필요 -> 관리에 절반의 인력/시간 할애 -> 새로운 문제는 절반으로 대응 +
지금까지 하던 작업을 절반 크기로 압축해야 한다

성공 사이클은 관리하기 어렵지만 팀을 확장하려면 거쳐야 하는 과정

문제를 압축하려면 팀 효율 극대화할 방법을 찾아야, 자신의 시간과 집중력을 더 커진 책임 범위에 맞춰 확장하는 방법도 배워야

=== 중요한 일 vs 급한 일

리더는 능동형보다 반응형 일의 비율이 커진다

중요한 일에 몰두하려면?

위임하기 (조직 내 다른 리더에게), 따로 정기적으로 시간을 내기 (급한 일만 하는), 추적 시스템 마련 (작업에 우선순위를 매기고 진행 상황을 추적하기)

=== 공 떨어뜨리기

중요한게 확실한 20% +
조금 급하거나 중요할 수 있는 60% +
급하지고 중요하지 않은, 지우거나 무시할 20%

상위 20% 에 집중하여 일을 골라내고, 다음 일들에 집중 +
80% 를 버릴 권한을 부여

중간 60 은 위임하지 않아도 가져가는 중간 리더가 나타나기도 +
진짜 중요한건 어떻게든 60을 넘어서 20으로 돌아온다

=== 에너지 관리하기

열정과 긍정적 사고를 잃지 않으려면, 개인의 에너지도 중요하다

* 나이가 들수록 지구력이 좋아진다 (????????)
* 자신의 에너지를 더 지능적으로 활용하는 방법을 배워간다 (휴가, 일과 단절, 주말, 휴식, 정신 건강 챙기기 날)