= 7. 엔지니어링 생산성 측정하기

== 측정하는 이유

엔지니어 각각의 생산성이 높아지면 소통 비용 증가를 억제하면서 사업을 키울 수 있다

생산성을 높이려면 무엇이 필요한지 이해, 엔지니어링 프로세스에서 비효율적인 부분을 찾아서 고침, 반복

엔지니어링 생산성을 이해하기 위한 전담 연구팀을 만들었다 +
-> 생산성 개선 + 업무 자체의 효율을 높이는 목표 +
-> 개인의 동기, 성과 보상 구조, 복잡한 작업 관리 전략 +
-> 엔지니어링 생산성을 측정하고 개선하는 데이터 주도 접근법을 만들어내는 것이 목표

프로세스에서 개선이 필요한 부분을 식별해낼 수 있는 지표를 찾아낸 방식 & 어떻게 활용했는지

== 선별: 측정할 가치가 있는가?

측정 자체도 비용이 많이 들기 때문

각 팀에 구체적인 질문을 던져서 측정하고 싶은 것을 설명하도록 한다 +
구체적으로 답할 수록 측정 과정에서 얻는게 많아짐

* 어떤 결과를 기대하고, 왜 그런가?
* 데이터가 기대한 결과를 뒷받침한다면 어떤 조치를 취하겠는가?
* 부정적인 결과가 나온다면 적절한 조치를 취할 것인가?
* 결과에 따른 조치는 누가 결정하고, 언제 수행하는가?
** 결정을 내릴 사람이 누구이고, 확신을 위해 어떤 데이터가 필요한지 이해해야 한다

측정해볼 가치가 없는 경우가 많다 +
도구나 프로세스가 생산성에 미치는 영향을 측정하지 말아야 할 이유들

* 당장 프로세스/도구를 변경할 여유가 없다.
* 어떤 결과가 나오든 곧 다른 요인에 의해 의미가 없어질 것이다
** 조직 개편 등의 다른 요인
* 측정 결과를 이미 확정된 계획을 뒷받침하는 용도로만 쓴다
** 결정을 이미 내려놓고 측정하는 경우
* 지표들이 문제를 평가하기에 정확하지 않고, 다른 요인들로 인해 혼탁해질 우려가 크다

== GSM 프레임워크: 목표와 신호를 뒷받침하는 의미 있는 지표 선정하기

* Goal, 목표: 원하는 최종 결과. 측정을 통해 이해하고 싶은 내용
* Signal, 신호: 원하는 최종 결과를 이루었는지 판단하는 방법
* Metric, 지표: 실제로 측정하는 대상

목표를 세우고 -> 신호를 정하고 -> 지표를 만든다

. 가르등 효과 없앰
** 보이는 곳만 봐서는 찾을 수 없다. 진짜 필요한 지표 인지를 보게 된다
. 지표 크리프와 지표 편향을 없애준다
** 측정 전 원칙에 입각하여 적절한 지표를 선정하게 해줌
. 측정이 되는 영역과 아닌 영역을 알려준다

추적 가능성을 잃지 않아야 한다 - 개별 지표에서 관련한 신호를 찾고, 신호의 목표를 추적할 수 있어야 한다. 지표가 무엇을 측정하고 왜 측정하는지를 알 수 있기 때문

== 목표

원하는 속성을 설명하되 지표를 명시해서는 안된다

특정 요소를 개선하느라 다른 요소를 희생하는 일이 없어야 한다 +

목표 다섯 요소 (QUANTS)

* 코드 품질, Quality of the code
* 엔지니어들의 몰입도, Attention from engineers
* 지적 복잡성, Intellectual complexity
* 박자와 속도, Tempo and velocity
* 만족도, Satisfaction

모든 엔지니어링 생산성 문제가 다섯가지 영역에 관련된건 아니다 (특정 영역에선 해당이 안될 수도 있음)

== 신호

묙표 당설 여부를 알 수 있는 방법

표 7-1 목표 - 신호 연결

== 지표

신호를 측정하는 방법의 최종 형태

모든 신호를 측정하진 못할 수 있어, 여러 지표를 종합하여 정확도를 높이기도

== 데이터로 지표 검증하기

구글에서 빌드 시간 측정 시 경험표집법 - 특정 사건을 경험한 직후 즉각적인 응답을 요구하는 연구 방법

정량적 지표 - 힘과 확정성을 준다, 엔지니어들의 경험을 회사 전반에 걸쳐 오랜 기간 측정할 수 있음 +
왜 구식 도구를 사용하는지, 비정상적인 워크플로우를 따랐는지는 설명할 수 없음 -> 정성적 연구에서만 가능

표 7-2. 묙표, 지표, 신호 (최종)

신호는 분석 도구와 코드 로그로 측정, 어떤 지표는 엔지니어들에게 직접 물어볼 수 밖에 없다 +
특화된 설문조사, 영향을 줄 것으로 기대되는 지표들을 추적하기 위해 분기별 대규모 설문조사, 엔지니어들이 특정 작업을 완료하는데 거린 시간을 알려주는 정밀 로그 지표 등

== 조치를 취하고 결과 추적하기

개선을 멈추지 않고 지속하는 방법을 담은 '추천 할 일 목록' 제공 +
기능 추가, 도구 지연시간 단축, 문서 보강, 낡은 프로세스 제거, 성과 보상 제도 구조, ...

이상적인 건 도구 개

== 마무리

'사람에 의한' 요인은 측정하기 어렵다 +
데이터 중심으로 판단하면서 주관적인 편향을 제거하는 걸 목표로 삼아야 한다