= 9. 코드 리뷰

== 흐름

변경을 코드베이스에 커밋하기 전에 수행 - precommit review

좋아보임 - LGTM (Looks Good To Me)

. 변겅사항 작성 -> 스냅샷 생성
. 초기 패치를 사용하여 자동 리뷰 의견 or 스스로 리뷰
** 한 명 이상의 리뷰어에게 메일을 보내 리뷰 요청
. 리뷰어들이 코드 리뷰 도구에서 변경을 열고 의견 코멘트
. 피드백을 기초로 수정, 새로운 스냅샷 업로드 후 회신
. 만족하면 LGTM
. 승인되면 커밋

== 구글에서의 코드 리뷰

'승인'을 얻으러면 세 가지 측면에서의 리뷰를 통과해야 한다

* 정확성 (correctness) 과 이해 용이성 (comprehension)
* 코드 소유자로부터 적절하다는 승인 의견
** 소유권과 그 크기는 팀이 결정
* 가독성 승인

대부분은 세 역할을 모두 수행할 수 있는 한 명이 처리하기 때문에, 빠르게 진행된다 +
본인이면 다른 엔지니어를 추가로 달아줄 엔지니어를 찾음

하지만 세 가지 역할을 나눠서 한다 - 확장성 때문 +
역할을 셋으로 나눔으로써 코드 리뷰 프로세스가 더 유연해진다

.소유권
****
레포를 쪼개거나 책임져줄 사람을 명시하는 방식으로 전환 - 소유권 & 소유자

소스 코드가 소유자의 것이라는게 아니라 회사의 추구하는 가치가 지켜지도록 관리한다는 의미의 소유
****

== 이점

=== 코드 정확성

변경된 코드의 정확성을 확인 +
변경에 적합한 테스트가 갖춰졌는지, 설계는 적절한지, 정확하게 동작하고 효율적인지, 버그를 심지 않도록

코드 리뷰 (최대한 가볍게 유지해야긴 한다) 에 들이는 시간이 테스트, 디버그, 회귀 테스트에 투입되는 시간을 줄여준다

변경 작성자가 선택한 방식을 존중 +
리뷰어가 대안을 제시할 순 있다 - 이해하기 더 쉽거나, 기능을 개선하는 대안일 경우

정적 분석이나 자동화 테스트로 수행하기도 한다

초기 코드 리뷰 프로세스에서 결함을 찾는 일은 원점 회귀 (shift left) 전략에 필수이다 +
shift left: 가능한 일찍 문제를 찾아서 비용을 낮추기

새로운 코드가 이해하기 쉽고 나중에 커져도 여전히 의미가 통할 것임을 알려주는 데에 이점

=== 코드 이해 용이성

코드 리뷰는 주어진 변경이 쉽게 이해되는지 평가하는 첫 시험대

리뷰어는 작성자가 선택한 설계를 존중해야 한다

=== 코드 일관성

일정한 표준을 따라야 한다 - 조직 안에서 이해되고 유지보수 될 수 있게 +
단순해야 이해하기 쉽고 유지보수하기 쉽다

코드 리뷰 과정에서 주어진 코드가 코드베이스의 표준을 얼마나 잘 따르는지 평가할 수 있다

=== 심리적, 문화적 이점

코드는 자신의 것이 아니라 조직의 공동 소유물임을 인식

코드 리뷰 프로세스는 리뷰어들에게 비판적으로 검토해달라고 만든 제도이다. 비판한다고 비난하면 안되는 것

검증 - 작업 결과를 검증하고 인정해주는 효과

자신의 코드를 한번 더 들어다보게 하는 효과

=== 지식 공유

리뷰 프로세스는 제안, 신기술 소개, 조언을 통해 리뷰어가 변경 작성자에게 도메인 지식을 전파하도록 함

양방향 정보 교환, 작성자와 리뷰어 둘 다 새로운 기술이나 패턴을 배울 수 있다

코드베이서의 변경 이력을 기록하는 역할도 한다

== 모범 사례

=== 공손하고 전문가답게

LGTM 을 남발하지 않고 어떤 피드백과 비평이라도 전문가답게

결함이 있을 때만 대안을 제시 +
방식이 잘못되었다고 가정하기 전에 이유가 무엇인지를 물어보기

작성자도 선택한 방식에 대한 질문들에 왜 그랬는지 설명할 준비를 해둬야 한다

리뷰어가 단 댓글은 모두 할 일 (TODO item) 로 취급해야 한다

=== 작게 변경하기

변경량이 적다면 버그가 생겼을 때 살펴볼 코드도 그만큼 적다

하지만 작은 변경은 개별 단위로는 쉽지만 큰 그림 안에서 종합적으로 검토하기는 어렵다

'작은' 변경은 변경되는 코드가 200줄 이하 +
대부분의 리뷰가 하루 내에 완료되리라 기대

=== 변경 설명 잘쓰기

어떤 종류의 변경인지를 잘 요약해야 한다

구체적으로 무엇을 왜 변경하는지 알려주는 자세한 설명도 필요하다

리뷰어가 코드를 이해하지 못한다면 구조를 개선하고나 주석을 더 잘 달아두어야 한다는 신호일 수도

=== 리뷰어는 최소한으로

리뷰어가 한 명 추가될 때마다 새로운 시각이 더해지고, 수확 체감 (diminishing returns) 으로 이어진다 (?)

리뷰어를 추가해서 얻는 가치보다 비용이 더 빠르게 증가한다

엔지니어들이 일을 올바르게 처리할 것이라는 신뢰를 바탕

=== 가능한 한 자동화하기

== 유형

그린필드 코드 리뷰, 동작 변경/개션/최적화, 버그 수정과 롤백, 리팩토링과 대규모 변경

=== 그린필드 코드 리뷰

새로운 코드를 대상으로 하는 코드 리뷰

설계 리뷰를 강도 높게 진행

API 가 합의된 설계에 부합하고, 테스트도 완벽히 이루어졌는지를 그린필드 리뷰에서 확인해야 한다 +
설계 문서와 함께 검토, 공개된 모든 API 에 단위 테스트 추가, 소유자 배정 (OWNERS 파일 추가)

=== 동작 변경, 개선, 최적화

그린필드 리뷰 지침이 그대로 적용 - 꼭 필요한 변경인지, 코드베이스를 개선하는지 +
죽은 코드나 낡은 코드 제거는 코드베이스를 건실하게 만드는 아주 멋진 방법

동작을 변경할 때는 테스트도 수정되어야 한다 +
최적화도 기존 테스트에 영향을 주지 않아야 하고, 벤치마크 결과를 리뷰어에게 제시해야 한다 (벤치마크 테스트 마련)

=== 버그 수정과 롤백

버그를 수정하면서 다른 문제까지 처리하진 말아야 한다 - 롤백을 어렵게 만든다

버그 수정 시 테스트도 보강해야 할 가능성이 크다 - 기존 테스트들이 충분하지 못했거나 특정 가정이 어긋났기 때문

롤백을 유발할 수 있는 모든 변경은 작고 원자적이어야 한다

=== 리팩토링과 대규모 변경

변경이 자동으로 생성 - 작성자가 사람이 아니라 기계

자동 생성된 변경이라도 리뷰어가 정확성과 적용 가능성을 확인