= 6. 클래스 설계

== Item 36. 상속보다는 컴포지션을 사용하라 (Prefer composition over inheritance)

관계가 명확하지 않을 때 상속을 사용하면 문제가 발생할 수 있다

* 하나의 클래스만을 대상으로도 할 수 있음 - 거대한 부모를 만든다
* 부모 클래스의 모든 것을 가져옴 - 불필요한 함수
* 이해하기 려움

컴포지션을 사용한다 = 객체를 프로퍼티로 갖고, 함수를 호출하는 형태로 재사용하는 것

=== 모든 것을 가져올 수밖에 없는 상속

상속은 계층 구조를 나타낼 때는 좋지만, 재사용을 위한 목적으로는 적합하지 않다

컴포지션이 무조건 좋지는 않고, 인터페이스로 다중 상속을 하는 선택지도 있다 (개인적으론 이거 선호)

=== 캡슐화를 깨는 상속

외부 활용도 중요하지만, 내부에서 어떻게 활용하는지도 중요하다 (HashSet add, addAll) 예제

delegation 도 가능 +
delegation 을 사용하지 않는 컴포지션이 이해하기 더 쉽고 유연하다

=== 오버라이딩 제한하기

open 클래스는 open 메소드만 오버라이드 할 수 있다 +
하위에서 final 을 붙여서 그 하위는 제한할 수 있다

=== 정리

상속은 명확한 'is-a' 관계일 때 사용하는게 좋다

== Item 37. 데이터 집합 표현에 data 한정자를 사용하라 (Use the data modifier to represent a bundle of data)

데이터들을 한꺼번에 전달해야 할 때

아래 메소드들을 자동으로 생성해 줌

* toString, equals, hashCode, copy, componentN

componentN 은 위치를 잘못 지정하면 문제가 발생할 수 있음, +
기본 생성자의 프로퍼티 명과 같은 이름을 사용하는 것이 좋다

link:../kotlin-in-action/7_overloading_and_convention.md#destructing-declaration[Destructing declaration (kotlin-in-action, 구조 분해 선언)]

=== Tuple 보다는 데이터 클래스 사용하기

Pair, Triple - 코틀린 기본 제공 튜플

튜플만 보고는 어떤 타입인지 예측할 수 없다, 현재는 지역적인 목적으로만 남아 있음

* 값에 간단하게 이름을 붙일 때
* aggregate 집합을 표현할 때

데이터 클래스 사용의 장점

* 리턴 타입이 명확해진다
* 리턴 타입이 더 짧아지고, 전달하기 쉬워진다
* 사용자가 다른 이름으로 변수를 해제하면 경고 출력

== Item 38. 연산 또는 액션을 전달할 때는 인터페이스 대신 함수 타입을 사용하라 (Use function types or functional interfaces to pass operations and actions)

SAM (Single-Abstract Method): 메소드가 하나만 있는 인터페이스

함수 타입으로 파라미터를 받게 되면

. 람다 표현식 or 익명 함수로 전달
. 메소드 레퍼런스 or 제한된 메소드 레퍼런스로 전달
. 선언된 함수 타입을 구현한 객체로 전달

typealias 로 함수 타입 이름을 붙일 수도 있다 + 파라미터도 이름을 가질 수 있다

destructing argument 도 사용할 수 있다

=== SAM 을 사용해야 할 때?

코틀린이 아닌 다른 언어에서 사용할 클래스를 설계할 때만

== Item 39. 태그 클래스보다는 클래스 계층을 사용하라 (Use sealed classes and interfaces to express restricted hierarchies, Prefer class hierarchies instead of tagged classes)

태그 클래스: 태그 (상수 모드) 를 가진 클래스 - 서로 다른 책임을 한 클래스에 태그로 구분해서 넣는다 +
단점이 많다 (p264)

sealed 클래스를 사용하면 책임이 분산되므로 깔끔하다

=== 태그 클래스와 상태 패턴의 차이

상태 패턴은 객체 내부 상태가 변화할 때, 객체 동작이 변하는 패턴

상태는 더 많은 책임을 가진 큰 클래스 +
상태는 변경할 수 있다

구체 상태는 객체를 활용해서 표현, sealed 클래스 계층으로 만들면 좋다

=== 정리

코틀린에서는 태그 클래스보다 sealed 클래스를 사용한 타입 계층을 만드는게 좋다

== Item 40. equals 의 규약을 지켜라 (Respect the contract of equals)

규약을 위반하면 일부 객체 또는 기능이 제대로 동작하지 않을 수 있다

=== 동등성의 정의

* 구조적 (structural): equals 메소드와 == 로 확인하는 동등성
* 레퍼런스적 (referential): === 로 확인하는 (주소값) 동등성

연산자 (==, ===) 로 다른 타입를 비교하는 건 허용되지 않음

=== equals 가 필요한 이유

두 인스턴스가 완전히 같은 객체인지 비교

data class 에서는 기본 생성자에 선언되지 않은 프로퍼티는 copy 로 복사되지 않는다

equals 를 직접 구현해야 하는 경우

* 기본 동작과 다른 동작을 해야 하는 경우
* 일부 프로퍼티만 비교
* data 를 붙이는 것을 원하지 않거나, 프로퍼티가 기본 생성자에 없는 경우

=== equals 의 규약

==== 반사적 (reflexive)

`x.equals(x) == true

==== 대칭적 (symmetric)

`x.equals(y) == y.equals(x)`

==== 연속적 (transitive)

`x.equals(y) == y.equals(z)` -> `x.equals(z) == z.equals(y)`

==== 일관적 (consistent)

`x != null, y != null` 이면 `x.equals(y)` 는 항상 같은 결과 리턴

==== null 과 관련

x 가 null 이 아니라면, `x.equals(null) == false`

=== 정리

직접 equals 를 구현하는 것은 좋지 않다, 구현해야 한다면 위의 규약을 만족시켜야 한다

== Item 41. hashCode 의 규약을 지켜라 (Respect the contract of hashCode)

=== Hash Table

컬렉션에 요소를 빠르게 추가, 추출 +
중복 불허: 이미 들어 있는지 확인이 필요

해시 함수는 빠르고, 충돌이 적으면 좋다

=== 가변성

요소가 추가될 때만 해시 코드를 계산

set, map 의 키로 mutable 요소를 사용하면 안되고, 하더라도 변경하면 안됨

=== hashCode 의 규약

* 객체를 변경하지 않았다면 결과가 같아야 한다 (일관성 유지)
* equals 의 결과가 같으면 hashCode 의 결과도 같아야 한다
* (선택) hashCode 는 최대한 요소를 넓게 퍼뜨려야 한다

kotlin 은 ide 레벨에서 equals 구현 시 hashCode 구현도 추천한다

=== hashCode 구현

equals 구현 시 hashCode 구현해주어야 한다

equals 비교에 사용되는 프로퍼티를 기반으로 해시 코드를 만들어야 한다

* 모든 해시코드의 값을 더함
* 더하는 과정마다 이전 결과에 31 을 곱해서 더해줌

stlib 에서 `Objects.hashCode` 같은걸 지원해주진 않는데, hashCode 를 직접 구현할 일이 없기 때문

== Item 42. compareTo 의 규약을 지켜라 (Respect the contract of compareTo)

* 비대칭적: `a >= b`, `b >= a` -> `a == b`
* 연속적: `a >= b`, `b >= c` -> `a >= c`
* 코넥스적: `a >= b`, `b >= a` 둘 중 하나는 참이어야 한다

=== compareTo 을 따로 정의해야 할지?

순서가 확실하지 않다면 비교기를 companion 레벨에 정의해두고 사용하는 것이 좋다 (p292)

=== compareTo 구현하기

top level 함수 제공 (compareValues, compareValuesBy)

== Item 43. API 의 필수적이지 않는 부분을 확장 함수로 추출하라 (Consider extracting non-essential parts of your API into extensions)

메소드를 멤버에 정의? 확장 함수로 정의?

우월한 건 없다, 장단점이 있다

확장은 따로 가져와서 사용 - 다른 패키지에 위치 - 직접 멤버를 추가할 수 없느 ㄴ경우

여러 라이브러리에서 여러 메소드를 받을 수 있고, 충돌이 발생하지 않는다

다른 확장을 할 가능성이 있다면 그냥 멤버 함수로 정의

가상이 아니다 - 상속 안됨

클래스가 아닌 타입에 정의

클래스 레퍼런스에서 멤버로 표시되지 않는다

=== 정리

필수는 멤버로, 필수적이지 않으면 확장 함수로

== Item 44. 멤버 확장 함수의 사용을 피하라 (Avoid member extensions)

가시성 제한을 위해 확장 함수를 멤버로 정의하는 것은 좋지 않다 - 가시성 제한을 못한다 (p298) +
-> 확장 함수 사용 형태를 어렵게 만들 뿐

* 레퍼런스를 지원하지 않음
* 암뭄적 접근 시 어떤 리시버가 선택될지 혼동
* 확장 함수가 외부에 있는 다른 클래스를 리시버로 바등ㄹ 때, 해당 함수가 어떤 동작을 할지 명확하지 않음 (p300)