= 1. 더도 덜도 아닌 딱 마이크로서비스

== Microservice 란

비즈니스 도메인을 중심으로 모델링된 독립적으로 배포 가능한 서비스

=== 비즈니스 도메인을 중심으로 하는 모델링

cross-service 변경을 최소로 줄이게끔 보증하는 방법을 찾아야 함

.Conway's law
[quote]
시스템을 설계하는 모든 조직은 ... 불가피하게 조직의 커뮤니케이션 구조를 본떠 시스템 구조를 만들어 낼 것이다

콘웨이의 법칙이 전통적인 3 Layer Architecture (UI, Backend, DBA) +
= 일하는 사람들끼리 조직

3 Layer Architecture 보다 각 도메인 별 서비스로 구분을 해야 한다

=== 데이터 소유권 문제

보통 Microservice 에서 DB 를 공유해서는 안된다는 생각 때문에 곤란해 한다

독립적인 배포 가능성을 원한다면 안정적인 인터페이스가 필수다

DB 가 대규모인 경우는 4장에서 자세히 다룰 예정

=== 장점

확장성, 견고성, 다양한 기술, 병렬 개발, 유연성, ...

=== 문제점

* 네트워크가 문제를 일으키는 상황을 해결해야 한다
** (이래서 네트워크 공부의 필요성이 조금..)
* 트랜잭션과 안전성을 포기해야 한다

=== 사용자 인터페이스

UI 분해도 고려해야 한다 (3장에서 볼 예정)

=== 기술

새로운 기술을 채택하는 데는 비용이 든다 & 분산 시스템과 관련된 수많은 문제와 씨름해야 한다

익숙한 기술 스택 활용하여 문제 이해 -> 문제를 해결하기 위해 기술 변경을 고려하는게 유용하다

=== 규모

Microservice 의 목표는 '가능한 한 작은 인터페이스를 유지하는 것'

규모에 대한 걱정은 버리고 두 가지를 집중

. 얼마나 많은 마이크로서비스를 다룰 수 있는가?
** 복잡성, 새로운 기술 적응 필요
** 저자는 점진적인 마이그레이션을 주장
. 혼돈 상황이 되지 않으면서 마이크로서비스를 최대한 활용하기 위해 경계를 정의하는 방법은?

=== 소유권

제품 소유자가 배포 팀으로 직접 작업, 배포 팀이 제품 라인을 중심으로 나란히 정렬 +
서비스가 비즈니스 도메인을 중심으로 정렬

== Monolith

책에서 모놀리스는 보통 배포 단위를 말하는 것

=== Single Process Monolith

모든 코드가 단일 프로세스로 묶어 포장

==== Modular Monolith

단일 프로세스가 별도 모듈로 구성되어 있고 독립적ㅇ로 동작할 수 있지만 +
배포를 위해서는 여전히 결합이 필요

=== Distributed Monolith

여러 서비스로 구성되는 시스템이지만 전체 시스템을 함께 배포해야 함

분산 시스템의 모든 단점 & 단일 프로세스 모놀리스의 단점을 포함

정보 은닉이나 응집력 같은 개념이 희박한 경우에서 등장

=== Thrid-Party Black-Box System

분해하기를 원하는 몇몇 외부 소프트웨어를 모놀리스로 간주 +
책에서는 기반 코드를 변경할 수 없는 시스템에서도 분해 기술을 사용할 수 있다 함

=== 문제점

배포 경합

=== 장점

간단한 배포 토폴로지, 간단한 개발자 워크플로우, 모니터링, 트러블 슈팅, 전 구간 테스트 등

코드 재사용을 단순하게

== Coupling, Cohesion

* 결합도: 한 가지를 바꾸면 다른 것도 바꿀 필요가 있는 ㅂ아식
* 응집력: 관련된 코드를 그룹으로 묶는 방식

=== Coupling

implementation (구현), temporal (시간적), deployment (배포), domain (도메인)

== Just Enough Domain-Driven Design

=== Aggregate

실제 도메인 개념의 표현으로 간주하는 모델, 수명주기가 있음, 독립된 단위로 취급

단일 마이크로서비스는 하나 이상의 다양한 Aggregate 의 수명주기와 데이터 저장소를 처리

=== Bounded Context

구현 세부사항을 숨긴다

하나 이상의 Aggregate 를 포함한다

=== Aggregate 와 Bounded Context 를 Microservice 에 매핑

잘 정의된 인터페이스로서 응집력의 단위를 제공, 둘 다 Service boundery 로 작동할 수 있음

더 작은 서비스로 분해하려면, Aggregate boundary 를 중심으로 분할하는 방법