= 2. 마이그레이션 계획하기

기존 시스템 아키텍처로는 이룰 수 없는 뭔가를 달성하기 위해, MSA 로 마이그레이션하는 전략 +
(단순히 누가 해서 좋다! 해서 하면 안됨)

.3가지 핵심 질문
****
* 무엇을 성취하기를 바라는가?
** 비즈니스가 달성하려는 목표와 연관되어 있어야 -> **최종 사용자에게 혜택을 기술하는 방식**
* 마이크로서비스 사용에 대한 대안을 고려했는가?
* 전환히 작동하고 있는지 어떻게 알 수 있나?
****

== 왜 마이크로서비스를 선택하려 하는가?

=== 팀 자율성 향상

자율 부서로 작업할 수 있는 권한과 책임 부여

==== 대안은?

코드 기반의 일부에 대한 소유권을 다른 팀에 부여

=== 시장 출시 기간 단축

기다릴 필요 없이 변경사항 배포

==== 대안은?

단계별 소요 시간을 확인하고, 고충이 발생하는 지점에 주목 +
단계를 병렬로 실행할 수도 있을 것

=== 부하를 다루기 위한 비용 효율적인 확장

개별 마이크로서비스의 독립적으로 확장

==== 대안은?

수직, 수평 확장 +
더 나은 대안 기술로 대체

=== 견고성 향상

독립적이고 개별적으로 배포 가능한 프로세스로 분해, 견고성 향상 +
네트워크 분할, 서비스 중단 등을 더 잘 견디는 방식으로 시스템을 설계할 기회를 열어 둔다

==== 대안은?

로드 밸런서, 큐 등의 부하 분배 매커니즘 등

=== 개발자 수 늘리기

=== 신기술 수용

서비스마다 선택지가 다양해질 수 있다

== 마이크로서비스는 어떤 경우에 나쁜 선택일까?

=== 불분명한 도메인

서비스 경계를 잘못 잡으면 많은 비용이 들 수 있다 - 잦은 서비스 변경, 과도하게 결합된 구성 요소

=== 스타트업

제품/사장 적합성의 기초를 확립하여, 수익성을 위한 확장일 때 수직적 확장을 위한 선택지가 될 수는 있으나

자금이 제한적인 소규모 조직일 가능성이 크다

=== 고객 설치형 소프트웨어와 관리형 소프트웨어

=== 좋은 이유를 못 찾겠다

== 균형 조정

핵심 목표를 방해하거나 주의를 흩트리는 부차적인 목표들은 뒤로 빠져야 한다 +
(팀 자율성 향상, 새로운 기술 사용 등)

그림 2-1. 슬라이더를 사용해 예상 가능한 경쟁 우선순위의 균형 조정

== 사람들과 함께

목표에 공감해야 한다

== 조직 변화 구현

그림 2-2

=== 위기감 조성

변화가 필요한 시점이라는 사실을 사람들이 이해하도록

=== 혁신 추진체 구성

충분한 인원의 사람들 - 배포 과정 바깥의 외부인들을 참여시키는 것 (후원자) +
운영과 동작 방식에 중대한 영향을 미칠 수 있기 때문

=== 비전과 전략 수립

어떤 변화를 희망하는지 (비전), 어떻게 갈 것인지 (전략)

=== 변화 비전 전달

비전 공유는 소규모로 시작해도 좋다 +
우선은 직접 대면하자

=== 광범위한 조치를 위한 직원의 자율권 강화

장애물을 제거하기

=== 단기적인 성과 창출

작고 손쉬운 결실에 초점을 맞추면 탄력을 받을 수 있다

=== 이익 통합과 더 많은 변화 추구

서우치한 것에 안주하지 않는 마음가짐이 중요하다

=== 혁신 문화의 정립

새로운 작업 방식이 일상으로 자리잡기 시작할 것이다

== 점진적인 마이그레이션의 중요성

[quote, 마틴 파울러]
빅뱅 방식으로 백날 해봐야, 빅뱅만 나올 뿐이다

모놀리스 분해가 필연적이라면, 조금씩 추출해 모놀리스에서 서서히 잘라내는 방식을 추천한다

=== 운영 환경은 중요하다

마이크로서비스의 추출은 운영 환경에서 활발히 사용되기 전까지는 완전한 것으로 간주될 수 없다

== 변화에 드는 비용

점진적인 변화 강조 이유? -> 변경의 영향력을 이해하고, 필요한 경우 방향을 바꿔야 한다

=== 가역적 결정과 비가역적 결정

마이크로서비스로 가면 더 많은 결정을 해야 되는데, 여기서 함정에 빠질 수 있다

비가역적일 수록 신중하게, 가역적이면 되돌릴 수 있지만 그 때의 비용을 반드시 고려해야 한다

그림 2-3. 비가역적 결정과 가역적 의사결정 사이의 차이점과 사례

=== 실험을 시도해볼 만한 곳

설계를 그려보고, 서비스 경계가 될 것으로 여기지는 곳에서 사용 사례를 실행할 때 어떤 일이 발생하는지 확인 +
어떤 호출? 이상한 순환 참조? 두 서비스 간에 지나치게 많은 호출?

== 도메인 주도 설계

도메인 주도 설계가 시작해야 할 지점을 잡는데에 도움이 될 수 있다

경계 컨텍스트는 잠재적인 분해 단위를 나타낸다

=== 작업 범위를 얼마나 넓게 잡야아 할까?

기능의 고수준 그룹화 측면에서 모놀리스에 대한 일반화된 모델 고안 -> 탐색이 필요한 부분을 선택

=== 이벤트 스토밍

기술 전문가와 비전문가가 다 같이 참여해 공유 도메인 모델을 함께 정의하는 협업 방식

모델에 대한 공통된 이해

=== 우선순위 지정을 위한 도메인 모델 사용

도메인 모델에서 의존이 적은 기능을 우선으로 선택

하지만 기능이 얼마나 얽혀 있는지 파악하려면 코드는 봐야 한다

데이터 저장소 분해는 초기에는 진행할 사항이 아니다

== 결합된 모델

분해로 얻는 가치와 난이도에 기반 그림 2-8 처럼 분류해야 한다

== 팀 재구성하기

새로운 개념을 활용하기 위해 조직을 변화시켜야 할 수도

=== 변화하는 구조

=== 만병통치약은 없다

문제를 해결하기 위해 맞는 조직 구조는 각자 다르다

소프트웨어의 전체 수명주기를 완전하게 소유하는 팀으로 전환하려면 +
팀의 기술에 변화가 필요하다는 사실을 이해해야 한다 -> 도움과 교육, 새로운 인력 충원

=== 변화 일으키기

소프트웨어 배포와 관련된 모든 활동과 책임을 명시적으로 나열하기부터 시작 (예시로 그림 2-9)

그림 2-10 처럼 결정했다면 그마다의 활동과 책임을 재배치

=== 전문 기술 변경하기

스스로 기술 수준을 평가하여 점수를 매기기 (기술 지도, skill map)

개인 예시 (그림 2-11) - 이거는 누군가 모아서 비공개로 유지 +
팀 예시 (그림 2-12) - 개인 예시를 취합하여 팀 단위로 공유

원하는 기술을 갖춘 새로운 사람을 팀에 데려와서, 그 전문가가 해당 분야의 학습을 돕도록 하자 +
(근데 그 전문가를 데려오려면 평가를 해야하는데, 그럼 그 평가는 누가?)

== 전환이 순조로운지 어떻게 확인?

추적 가능한 몇 가지 측정 방법 정의

"잘 되고 있는가?" 가 아닌 "다른 뭔가를 시도해봐야 하지 않을까?" 를 질문해야 한다

=== 정기 점검 사항

정기적인 회고 활동 or 주기적인 중간 완료 마일 스톤에서 명시적인 활동으로 계획

. 마이크로서비스로 가서 기대하는 바가 무엇인지
. 운영 과정에서 정량적인 측정 데이터 검토, 진척 사항 확인
. 정성적인 피드백 요청
. 무엇을 변화시킬지 결정

=== 정량적인 측정

배포 주기, 배포 수, 실패율, 성능 테스트 등 각자에 맞는 지표를 정하여 수집

지표는 위험할 수도 있다 - 길들여질 수 있음

단계를 작게 나눠 수행하는 방식이 중요하다 - 변화가 작을수록 부정적인 영향이 줄고, 문제가 발생했을 때 더 빠르게 해소

=== 정성적인 측정

팀원들의 감정에 대한 점검사항도 넣어야 한다 - 업무를 즐긴다면 훌륭하다, 아니면 조치가 필요할 수도

=== 매몰 비용 오류 방지

단계를 작게 만들면 매몰 비용 오류의 함정을 피하기가 좀 더 쉬워진다

=== 새로운 방식에 마음을 열자

끊임없이 개선하는 문화를 수용하고 항상 새로운 것을 시도하려 노력하면, 방향을 바꾸는 과정이 더 자연스러워진다