= 3장. 기본 도구

== Topic 16. 일반 텍스트의 힘 (The Power of Plain Text)

기본 재료는 지식 -> 설계와 구현, 테스트, 문서로 표현 +
-> 지식을 저장하는 최고의 포맷이 plain text 다

=== Plain text ?

인쇄 가능한 문자, 정보를 전달하기 적합한 형식

[NOTE]
====
Tip 25. 지식을 일반 텍스트로 저장하라.
====

=== 텍스트의 힘

* 지원 중단에 대한 보험
** 포맷을 부분만 알아도 파싱할 수 있다
* 기존 도구의 활용
** 컴퓨터 세계의 거의 모든 도구는 일반 텍스트를 다룰 수 있다
* 더 쉬운 테스트
** 특별한 도구를 만들 필요 없이 간단하게 테스트 데이터를 추가하거나 수정할 수 있다

== Topic 17. 셸 가지고 놀기 (Shell Games)

GUI 는 보는 것이 얻는 장점이 있지만, 보는 것이 얻는 것의 전부라는 단점이 있다 +
= 설계자가 의도한 범위를 넘어설 수 없다

[NOTE]
====
Tip 26. 명령어 셸의 힘을 사용하라.
====

== 자신만의 Shell

색깔 조합 설정, 프롬프트 설정, alias & shell function, 명령어 자동 완성

https://chanhy63.tistory.com/13[예전에 글 써둔 것]

== Topic 18. 파워 에디팅 (Power editing)

각각의 에디터에 유창해지도록 노력해야 한다.

[NOTE]
====
Tip 27. 에디터를 유창하게(fluency) 쓸 수 있게 하라.
====

지금의 나는?

* IntelliJ: java, kotlin
* vscode: json, plain text, asciidoc, helm chart, ...

삶을 편하게 해주는 명령어를 배워라 +
한계에 봉착한다면 확장 기능을 찾아보라

== Topic 19. 버전 관리 (Version Control)

거대한 실행 취소, 공동 작업, 배포 파이프라인, 이슈 추적, 팀 상호작용

변경 사항 추적, 버그 추적, 감사, 성능 관리, 품질 관리

[NOTE]
====
Tip 28. 언제나 버전 관리 시스템을 사용하라.

소스 코드, 문서, 메모, 빌드 및 릴리즈 절차, 스크립트, ...
====

p123 프로젝트 허브로써의 버전관리 - github 에 다 있는 듯

== Topic 20. 디버깅 (Debugging)

[NOTE]
====
Tip 29. 비난 대신 문제를 해결하라

다른 사람의 버그를 비난하기보다 문제를 고치는 데 집중
====

겉으로 드러난 것만 보지 말고 근본 원인을 찾으려고 노력

경고 없이 빌드되는지부터 확인 +
자세한 정보를 얻기 위해 직접 재현하는 것도 확인해야 할 수도

[NOTE]
====
Tip 31. 코드를 고치기 전 실패하는 테스트부터.
====

=== 로깅과 트레이싱

시간에 따라 변하는 것을 관찰

tracing 구문 - 진단용 메시지 -> 몇 가지 오류를 진단하는 데 효과적 +
규칙적, 일관된 형식의 메시지여야 한다 - 자동으로 분석해야 할 수도 있기 때문

[NOTE]
====
Tip 34. 가정하지 말라. 증명하라.
====

버그 발견 시

* 고치는 것을 넘어 왜 일찍 발견되지 않았을 지 생각
** 테스트를 수정할 필요가 있을 지 확인
* 동일한 버그가 있을 법한 다른 코드가 있는지 확인
* 시간이 오래 걸린다면 왜 그런지 자문
* 다른 가정으로 발생했다면, 팀과 함께 토론

== Topic 21. 텍스트 처리 (Text Manipulation)

[NOTE]
====
Tip 35. 텍스트 처리 언어를 익혀라.
====

== Topic 22. 엔지니어링 일지 (Engineering Daybooks)

* 기억보다 믿을만 하다
* 진행 중인 작업과 관계 없는 발상을 쌓아 놓을 수 있다
* 하던 일을 돌아보기에 알맞은 기회