= 4. 실용주의 편집증

== Topic 23. 계약에 의한 설계 (Design by Contract)

프로그램의 정확성을 보장하기 위해 소프트웨어 모듈의 권리와 책임을 문서화하고 합의 +
정확한 프로그램 = 딱 그만큼만 하는 프로그램

precondition, postcondition, class invariant

(TDD 식으로 테스트를 먼저 작성해서 맞추는 것도 계약으로 볼 수 있을까? -> p152 에서 바로 나옴)

.DBC 와 테스트 주도 개발
****
테스트와 비교했을 때 DBC 의 장점

* 테스트 환경 구성이나 mock 이 필요 없다
* 모든 입력값에 대한 성공과 실패 정의
* 설계, 개발, 배포, 유지보수 전체에 걸쳐 사용
* 방어적 프로그래밍보다 더 효율적이다

TDD 는 정상 경로에 집중하지만, 실제는 나쁜 데이터, 사람들, 버전, 명세로 가득하다
****

=== DBC 구현

코드를 작성하기 전에 조건들을 나열하는 것만으로도 도움이 된다

컴파일러가 계약을 검사하도록 하거나 +
assertion - 실행 시점에 검사하도록 하기 (단정문을 부분적으로 흉내낼 수 있다) +
부분적인 이유는 언어마다의 제약이 다르기 때문 (상속하면 없어진다거나..)

=== DBC 와 일찍 멈추기

검증하면 더 일찍 멈추고, 문제에 대한 정확한 정보를 알려줄 수 있을 것이다

연산을 시도하다 예상 밖의 결과를 얻는 시점이 한참 나중일 수도 있다

=== 의미론적 불변식 (semantic invariant)

무언가를 품은 진짜 의미의 중심, 일시적인 정책에 영향을 받으면 안된다 +
찾은 후에는 잘 드러나는 곳에 위치해야 한다

== Topic 24. 죽은 프로그램은 거짓말을 하지 않는다 (Dead Programs Tell No Lies)

일찍 작동을 멈춰라

빨리 문제를 발견하면 빨리 시스템을 멈출 수 있다

죽은 프로그램이 끼치는 피해는 이상한 상태의 프로그램이 끼치는 피해보다 훨씬 적다

== Topic 25. 단정적 프로그래밍 (Assertive programming)

[NOTE]
====
Tip 39. 단정문으로 불가능한 상황을 예방하라.
====

진짜 오류를 처리해야 하는 곳에는 사용하지 말기 (절대 일어나면 안되는 것들만 검사) +
assert 는 프로세스를 종료?

side effect 가 있는걸 단정문에 넣을 수 있으니 주의

단정 기능을 켜두어라

== Topic 26. 리소스 사용의 균형 (How to Balance Resources)

[NOTE]
====
Tip 40. 자신이 시작한 것은 자신이 끝내라
Tip 41. 지역적으로 행동하라 (스코프를 줄여라)

리소스를 할당하는 함수나 객체가 리소스를 해제하는 책임을 져야 한다
====

=== 중첩 할당

* 리소스를 할당한 순서의 역순으로 해제
* (코드의 여러 곳에서) 같은 순서로 할당하여 deadlock 방지

=== 객체와 예외

특정 유형의 리소스를 클래스 안에 캡슐화하여 사용 +
-> GC 에서 객체를 수거해가면 리소스도 같이 해제

=== 균형 잡기와 예외

* 변수 스코프 사용 (C++, Rust)
* finally 사용
** kotlin 은 use 도 있음

=== 균형을 점검하기

리소스가 적절하게 해제되었는지 점검하는 코드 작성

리소스 종류 별로 wrapper 를 만들고 할당/해제 기록 보관 - 상태가 올바른지 점검

== Topic 27. 헤드라이트를 앞서가지 말라 (Don’t Outrun Your Headlights)

[NOTE]
====
Tip 42. 작은 단계들을 밟아라. 언제나.
====

작은 단계들 - 더 진행하기 전 피드백을 받고 조정 +
피드백의 빈도를 제한 속도로 생각

볼 수 있는 미래까지만 고려 +
-> 언제나 교체 가능한 코드 작성, 무언가로 대체 가능하기 쉽게 설계 +
-> 이런 설계가 응집도, 결합도, DRY 등 더 나은 설계로 될 것