= 10. 전체 XP 팀

'전체 팀' 실천방법: 프로젝트를 효율적으로 만들기 위해서는 다양한 종류의 사람들이 서로 의견을 주고받으면서 일해야 한다

== 테스터 (Testers)

구현 전에 자동화된 시스템 차원의 테스트 (system-level test) 를 작성하는 일을 돕고, 프로그래머에게 테스트 관련 기법 지도

기능 구현 전 시스템의 기능이 만족스럽다고 말할 수 있는 기준 정의 및 명시

일주일별 주기 (Weekly Cycle) 에서 스토리륻 선택하면, 그걸 system-level test 로 바꾸는게 바로 다음 일이다

이번주 대상 테스트 작성 + 실패 확인 후에도 새로운 세부사항이 드러날 때마다 새로운 테스트 작성 +
(이게 진정 QA 인듯)

== 상호작용 설계자 (Interaction Designers)

시스템의 전반적인 메타포 선택, 스토리 작성, 이미 배포된 시스템의 사용 양상 조사 +
최종사용자의 문제를 해결하는 것이 최우선순위

고객이 스토리를 작성하고 명료하게 만드는 일을 도우면서 고객들과 함께 일한다 +
시스템 사용 양상을 분석하여 다음 일이 무엇인지 결정

초기 명세는 조금 -> 프로젝트 내내 사용자 인터페이스를 다듬는다

== 아키텍트 (Architects)

대규모 리팩토링을 찾아내고 실행, 아키텍처를 검증하는 시스템 차원의 테스트 작성, 스토리 구현

프로젝트가 발전하는 동안 아키텍처의 방향을 잡아준다 +
시스템이 작으면 그에 맞는 아키텍처, 커지면 증가에 발맞춰 커지게 함

테스트는 아키텍처의 의도를 말해 줄 수 있음 +
아키텍처를 개선하고 싶은 경우 시스템이 무너질 때까지 스트레스 테스트

시스템을 구획짓는 것 - 일을 divide-and-conquer 대신 계속 divide +
갈라지는 금들을 찾아 상대적으로 독립된 부분으로 나누고, 부분을 확장 +
가장 적합하게 갈라지는 금 선택을 도우고, 머리 속에 큰 그림을 유지하며 시스템 전체를 따라감

== 프로젝트 관리자 (Project Managers)

팀 내 의사소통이 용이하도록하고, 고객 & 공급자 & 조직의 다른 부분과의 의사소통 조정 +
프로제트 진전 정도를 상기, 프로젝트 관련 정보를 잘 포장 +
정확성을 위한 정보의 잦은 갱신

계획 짜기는 단계가 아닌 활동이다 -> 계획과 현실이 계속 일치하도록 유지할 책임이 있다

정보는 팀 안팎으로 흐른다. 모든 팀으로 오는 의사소통을 용이하게 한다 +
팀 내부 의사소통 또한 용이하도록 하여 응집성과 자신감을 높인다 - faciliator

== 제품 관리자 (Product Managers)

스토리 작성, 분기별 주기 및 일주일별 주기에서 주제와 스토리를 고르고, 스토리에서 완전하게 명세되지 않은 부분이 드러날 경우 질문에 답변하는 역할 +
XP 에서 계획: 어떤 일이 가능한지 O, 어떤 일이 일어날지 X

일이 너무 많으면, 유구사항을 분석하여 가려내어 우선순위를 결정하는 일을 도움 +
당장 일어나는 일에 맞추어 스토리와 주제 조정

목표는 첫 주부터 작동하는 시스템을 만들어 내는 것이다

특정 기능의 동작이 우선인데 이전 필요 조건들이 없다면, 가짜 데이터 집합을 정의하여 그걸 기반으로 구현

시스템은 첫 일주일별 주기가 끝날 때쯤 '전체를 담고 있어야' 한다 (이미지 처리 계획? -> 첫 주말에 이미지 처리 가능) +
제품 관리자는 이게 되도록 스토리를 고름

== 임원 (Executives)

XP 팀에 용기, 자신감, 책임감을 불어넣는다 +
규모가 큰 목표르르 뚜렷하게 표현하고 유지하는 일 (팀 목표 != 회사 목표 or 압력 등으로 인해 목표가 흔들림에서 자유롭게) +
개선을 감시, 권장, 조장 +
프로젝트에서 어떤 점에서든 자유롭게 설명을 요구할 수 있고, 그건 이해할 수 있어야 한다

어떤 선택사항에 대한 정직하고 명료한 설명을 들으리라 기대할 수 있어야 한다 +
장기적인 시야 유지, 범위를 축소해야 할 때는 조직에 필요한 것과 프로젝트의 요구사항에 초점

XP 팀이 얼마나 건강한지 측정

. 개발 후에 발견된 결함의 개수
** 첫 번째 배포에도 결함 수를 줄여야 하고, 그 지점부터도 빠른 발전을 해야 함
. 투자를 하는 시점과 처음 수익을 발생시키는 시점의 차이

기대치를 달성하지 못해도, 다른 부분에 긍정적으로 보이게 만드는 일도 임원의 임무 +
비판에 맞서서 계속 일을 진행시킬 용기를 내는 것

== 테크니컬 라이터 (Technical Writers)

기술적 출판물의 역할 = 기능에 대한 빠른 피드백을 제공 + 사용자들과 더 긴밀한 관계를 맺는 것 +
기능의 구상 단계일 때부터 처음으로 그 기능을 보는 사람이기 때문 (어떻게 설명할지 고민)

고객과 더 긴밀한 관계를 맺음 - 고객에게 귀 기울여서 출판물 (사용 설명서, 참조 설명서, 기술적 개요, 비디오, 오디오) 등으로 반영

XP 개발 시스템의 변화 속도는 기술적 출판물을 만드는 일을 어렵게 만든다 -> 개발 명세가 마지막까지 고정되지 않음 +
(이래서 나중에 스펙 헷갈리긴 하는데, 명확하게 정리한게 있으면 좋을 듯) +
이번주 스토리를 다음주 문서화 작업으로 삼으면 일주일 늦어도 만들 수 있고, 같은 주에 완성하는 것도 도전

완벽한 문서화란?

* 문서에서 서술하는 기능이 막 구현된 시점에 문서 작성도 완료되고
* 문서에서 개선할 점이 발견될 때 갱신하기 쉽고
* 만드는데 비용이 적게 들고
* 기본 개발 주기에 시간을 더하지 않아도 되는 것
* 사용자에게 가치 있는 것
* 문서를 작성하는 작업이 팀에게도 가치 있는 것

== 사용자 (Users)

스토리를 작성하고 고르는 일을 돕고, 개발 중에 문제 영역에 관련된 결정을 내림 +
지금 만드는 시스템들에 대한 광범위한 지식과 경험 겸비, 시스템이 완전히 배포되면 실제 사용자 공동체와 튼튼한 관계를 맺는 사람 - 전체 공동체를 대변

== 프로그래머 (Programmers)

스토리와 과업 추정, 스토리 -> 과업으로 나누기, 테스트 작성, 구현 코드 작성, 개발 프로세스 자동화, 시스템의 설계를 점진적으로 개선

== 인적자원부 (Human Resources)

평가와 채용

=== 평가

* 다른 사람을 존중하는 행동
* 다른 사람과 잘 어울림
* 솔선수범
* 자신이 약속한 것을 지킨다
* 개인별 (목표, 평가, 임금 인상)
* 팀 기반 (보상, 임금 인상)
* 개인별 + 팀 혼합 (평가와 임금 인상: 개인별, 상여금: 훌륭한 팀워크)

=== 채용

팀워크와 사회적 기술에 비중을 둔다

== 역할 (Roles)

역할은 고정된 것이 아니다

한 사람 당 한 역할이라는 단순한 mapping 은 아니다


== 읽으면서 드는 생각

* 여태는 무언가 명확한게 주어져야 개발을 시작했는데 이게 잘못된건가 고민