= 15. XP 확장

소프트웨어 개발 규모는 사람 숫자 뿐 아니라 다른 여러 차원에서도 확장될 수 있다

== 사람 숫자

적을 때의 방법이 커졌을 때는 효과를 내지 못한다

. 큰 문제를 작은 문제로 변환
. 단순한 해결방법을 적용
. 문제가 남은 경우 복잡한 해결방법을 적용

시스템(팀)을 분할할 경우 팀마다 다르게 내린 가정을 조정할 수 있도록 자주 통합한다. +
-> conquer-and-divide (이게 어딜봐서?)

=== conquer-and-divide

팀 간 조정 비용을 절약하기 위해, 각자 유일한 팀인거처럼 작업 +
독립 팀으로 할 수 없는 예외는 예외로 관리 -> 일상으로 전환 +
서로 다른 팀이 조정하는데 시간이 많이 들면 다시 독립적일 수 있게 시스템 재구성 방안 찾기

== 투자

(???)

소프트웨어 개발을 어떻게 회계처리 할 것인가 (비용, 자본 투자)

주기별 or 년별 주기 -> 범위가 상세하게 결정되지 않았더라도 사용할 수 있음

재정, 재무와 친해져라

== 조직의 크기

변화하지 않는 조직의 일부분에 XP 적용하기 +
-> 새로운 작업 방식을 하지만, 변화를 강요하는게 아니다 +
-> 조직의 다른 부분과 의사소통할 때에는 그들에게 익숙한 형식이 유지되도록 해두어야 한다.

프로젝트 관리자는 정보를 조직이 흡수할 수 있는 형식으로 보여주어야 한다.

== 시간

시간 규모를 확장하는

* 가장 단순한 경우: 팀의 지속성이 유지됨
** 자동화된 테스트와 점진적 설계가 시스템이 계속 살아 있고 성장할 수 있도록 지탱
* 어려운 경우: 프로젝트가 자주 시작되었다가 멈추고, 팀이 모였다 흩어졌다 함
** 프로젝트를 중지하기 전에 '로제타석' 문서를 작성
*** 미래의 유지보수자를 위한 간략한 지침서
*** 빌드-테스트 절차의 실행 방법, 시스템을 학습하기 좋은 시작점
*** (이거는 그냥 대부분에 적용하고 있는 듯, 사람이 오가는건 자연스러운거니까)

== 문제의 복잡도

전문 영역에 대해 조금씩 배우는 동안 조화롭게 일하도록 만들기

모르는 영역을 천천히 배우면서 일하면 시간이 지나면서 역으로 도움을 줄 수 있다

== 해결방안의 복잡도

문제에 걸맞지 않게 크고 복잡한 시스템 = 과잉된 복잡성

제품을 계속 deliver 하면서 복잡성을 깎아 나가기 +
결함을 고치는 동안 깔끔하게 정리하기 (일의 부하를 줄임)

== 실패의 결과

생명이 달린 (항공, 의료) 상황에서는 실수가 죽음으로

안전, 보안 등 밀접하게 연관된 것들에 대한 실천방법들은 팀의 매일 작업에 포함되어야 한다