= XP 란 무엇인가?

사회적 변화 = 방해가 되는 습관, 양식을 버리기 = 생산성을 떨어뜨리는 방어수단들을 포기 = 우리가 할 수 있는게 무엇인지 공개, 해결

extreme = 성공을 준비, 최선을 다한 다음 결과에 대처, 자신을 노출

== XP 에 포함되는 것

* 의사소통, 피드백, 단순성, 용기, 존중 등의 소프트웨어 개발 철학
* 소프트웨어 개발 개선 실천방법들의 집합. 실전 방법들은 서로 보완하고 효과 증폭
* 상호 보완적인 원칙들. 가치 -> 실천방법으로 옮기는 지적인 기법들의 집합
* 이 가치들, 실천방법들 중 상당수를 공유하는 공동체

== 다른 방법론과 다른 점

* 짧은 개발 주기: 개발 초기부터 구체적이고 지속적인 반응
* 점진적 계획 접근: 전반적인 계획을 빨리 만들고 시작. 계획이 진화될 것으로 기대
* 자동화된 테스트에 의존: 진전 상황 관찰, 시스템 진화할 수 있게 함, 초기부터 결함을 잡을 수 있게 함
* 구두 전달, 테스트, 소스코드에 의존하여 시스템 구조와 의도를 전달
* 계속적으로 진화적인 설계 절차에 의존
* 참여자들 사이의 긴밀한 협력에 의존
* 단기, 장기 둘 다에 함께 적용될 수 있는 실천방법들에 의존

== 그래서 XP 란? (초반)

1판에서의 XP = 모호한 요구사항이나 빠른 속도로 변하는 요구사항에 직면한 중소 규모의 소프트웨어 개발 팀을 위한 가벼운 방법론

2판에서는?

* 가볍다
** 목표 달성을 위해 꼭 필요한 일만 함
* 소프트웨어 개발의 제약 조건을 다루는 방법론
* 팀의 규모와 상관없이 할 수 있다
** 실천방법들은 사람이 많은 경우 보충, 수정 필요가 있다
* 모호하거나 빠른 속도로 변하는 요구사항에 적응한다

== 개발 프로세스의 위험에 대처하기

=== 일정 밀림

릴리즈 주기가 짧아야 한다 +
일주일 단위의 iteration 으로 기능 구현, 진전 상황에 대한 작은 단위의 피드백을 주고 받는다

하나의 iteration 안에서 계획 단위는 짧은 task 들 +
우선순위가 높은 기능부터 구현해야 한다

=== 프로젝트 취소

비즈니스에 가장 중요하면서도 가작 작은 릴리즈를 고르라고 요구 +
(이게 기능 쳐내는거랑 비슷한건가..)

배포 전 잘못될 가능성은 적어지고 소프트웨어의 가치는 최고를 유지

=== 시스템 이상

포괄적인 자동화 테스트 스위트를 만들고 유지 +
시스템에 변화가 생길 때마다 수행 +
언제나 배포가 가능한 상태로 유지, 문제 축적 불허

=== 결함 비율

함수 단위 테스트, 프로그램 기능 단위 테스트 둘 다의 관점에서 테스트 (통합 테스트?)

=== 비즈니스에 대한 오해

비즈니스 팀도 first-class 구성원이 되어야 한다

=== 비즈니스의 변화

릴리즈 하나를 개발할 때 반영해야 하는 변화의 양이 줄어든다 +
아직 완성되지 않은 기능 대신 새로운 기능을 요청할 수 있다

=== 이름뿐인 풍부한 기능

우선순위가 가장 높은 작업만 다룰 것을 요구

=== 직원 교체

프로그래머들이 자신의 일을 추정하고 완료하는 책임 +
추정이 정확해질 수 있도록 실제 걸린 시간을 피드백 해주어야 한다

새로운 팀 구성원은 단계적으로 더 많은 책임을 받아들이도록 격려, 도움

== 그래서 XP 란? (마무리)

* 오래되고 효과없는 습관을 버리고 새로운 습관 채택
* 오늘의 내가 한 노력에 대해 자신을 인정
* 내일은 좀 더 잘해보려고 애쓰는 것
* 팀 전체가 공유하는 목표에 얼마나 기여했는지 자신을 평가
* 개발 도중에도 인간적 욕구 중 일부를 채우겠다고 요구하는 것

