= 가치

소프트웨어 개발은 개인이 팀의 일원이나 조직의 일원으로서 어떻게 행동하느냐가 중요하다

개발을 이끌기 위한 다섯 가지 가치

== 의사소통

어떤 문제에 맞닥뜨릴 경우, 의사소통의 부재가 문제인지 확인해보자 +
문제 해결을 위해 어떻게 의사소통? 앞으로 이걸 피하려면 어떻게 의사소통?

한 팀이라는 느낌을 만들고 협동하려면 의사소통이 중요하다

ex) 과거 비슷한 문제를 경험한 이야기를 듣거나, 팀 전체가 모여 재발 방지 논의 등

(5장 원칙 부분에서 글로만 하는 것에 대한 단점이 나오는데, 요즘 비대면에서 이게 좀 크게 와닿는듯)

== 단순성

단순한 시스템을 만들기 +
불필요한 복잡성을 제거하는 쪽으로 생각하기

의사소통을 개선하면 불필요하거나 미룰 수 있는 요구사항을 제거할 수 있으므로 단순성을 성취하는데 도움이 된다

== 피드백

처음부터 제대로는 어렵다 (어떻게 제대로하는지, 오늘은 제대로 도는게 내일은 안도는 경우, 제대로에 시간이 많이 걸려서 상황이 바뀜)

한 번에 완벽보다 점진적 개선

* 어떤 생각에 대한 개인 및 팀의 의견이 어떤가
* 생각 -> 구현 시 코드가 어떤가
* 테스트를 쉽게 작성할 수 있는지 아닌지
* 테스트가 도는지 아닌지
* 구현, 배포 후 어떻게 작동하는지

최대한 빨리, 많은 피드백을 만들기 위해 노력 -> 빨리 알 수록 빨리 적응

피드백이 너무 많으면? = 피드백 주기의 속도를 늦춰야 한다

피드백은 의사소통의 핵심이고, 단순성에도 기여한다. 단순할 수록 시스템에 대한 피드백도 더 쉽게 받을 수 있다

== 용기

두려움을 어떻게 다루는지 +
문제가 무엇인지 알면 무엇이든 해보는 것 +
문제가 있지만 정확히 모르면 기다리기 (인내)

용기는 다른 가치들과 조화를 이룰 때 좋다 +
의사소통 시 진실을 말 할 수 있는 용기 등

== 존중

생산성, 인간성을 동시에 개선하려면 팀에 속한 모든 개인의 기여를 존중

== 다른 가치들

조직, 팀, 개인 단위로 다른 가치를 선택할 수 있다

안정성, 보안, 예측가능성, 삶의 질 등