= 원칙

가치는 추상적이어서 직접적인 지침으로 삼을 수 없음

== 인간성

* 기본적인 안전: 배고픔, 물리적 상해, 위협, 실직
* 성취감: 자신이 기여할 수 있는 기회와 능력
* 소속감: 소속 내의 존재 이유와 책임감, 공유하는 목표에 기여할 수 있는 능력
* 설장: 자신의 기술과 시야를 확장할 수 있는 기회
* 친밀감: 다른 사람을 이해하고 이해 받을 수 있는 능력

== 경제성

돈의 시간적 가치 + 시스템과 팀의 선택적 가치

== 상호 이익

활동에 관련된 모든 사람에게 이익이 되어야 한다

ex) 내부에 대한 문서를 대량으로 작성하는 것은 상호 이익 원칙에 위배 +
현재 개발 속도를 떨어뜨린다

미래와 의사소통하기

* 더 나은 설계와 구현을 하도록 도와주는 자동화된 테스트들을 작성
* 복잡성 제거를 위해 신중하게 리팩토링
* 일관성있고 명시적인 메타포 집합에서 네이밍

== 자기 유사성

어떤 해결책의 구조를 다른 맥락에, 규모의 차이가 있는 다른 맥락에 그대로 적용해보기

실패하는 테스트 작성 -> 테스트 통과 +
해결하고 싶은 주제 목록 -> 스토리 여러 개로 나누어 해결 -> 스토리를 표현하는 테스트 작성 -> 테스트 통과

== 개선

완벽하다는 없다. 완벽해지도록 노력한다

개선을 통해 탁월한 소프트웨어 개발에 도달 +
오늘 최선을 다하고 내일 더 잘하기 위한 깨달음과 이해를 구하려고 노력

== 다양성

다양한 종류의 기술, 사고방식, 시야

다양성으로 인한 문제를 해결하기 위해 협동할 것과 모든 의견을 존중할 것을 관한다

== 반성

어떻게 일하는지, 왜 일하는지 +
왜 성공했는지, 왜 실패했는지

반성은 일 외에 일상적인 시간에서도 할 수 있다

== 흐름

개발의 모든 단계를 동시에 작업함으로써 가치 있는 소프트웨어를 끊임없이 제공

배포 주기와 연관

== 기회

문제가 있을 때 생각을 전환하여 기회로 보자

장기 계획 어려움? -> 분기별 주기 실천, 주기 안에서 장기 계획 +
혼자 일하면 실수? -> 페어 프로그래밍

== 잉여

해결 방법을 여러개 마련해 놓아야 한다 +
잉여를 만드는게 없는거 보단 이득이 크다

== 실패

성공이 어려우면 실패 -> 교훈을 얻을 수 있다

실패가 지식을 늘려주면 허비가 아니다

(약간 가치의 용기에 대응되는 내용인듯)

== 품질

품질을 희생하는 것은 관리 수단으로 삼기에 효과적이지 않다

품질보다는 범위 (scope) 를 관리 수단으로 사용해라 +
(범위는 무엇인가)

최대한 지금 할 수 있는 방법으로 잘 해두고, 나중에 확실한 방법으로 마무리 지을 결심

== 아기 발걸음

중요한 변화를 몰아서 하는 것은 위험하다

단계를 쪼갤 때 생기는 부하가 변화를 시도했다가 실패하는 것보단 작다는 것을 인정

== 받아들인 책임

일을 하겠다고 한 사람이 평가도 내리는 것

구현 책임 -> 설계, 구현 테스트까지 택임

== 결론

원칙을 이용하면 실천방법들을 더 잘 이해할 수 있다

원하는 실천방법이 없을 때 고안해낼 수 있다