= 2. 데이터 모델과 질의 원어

데이터 모델 - 소프트웨어가 어떻게 작성됐는지 + 해결하려는 문제를 어떻게 생각하는지애 영향

데이터 저장과 질의를 위한 다양한 범용 데이터 모델 & 다양한 질의 언어 볼 예정

== 관계형 모델과 문서 모델

1970년, 관계형 모델을 기반으로 한 SQL +
데이터는 releation 으로 구성, 각 관계는 순서 없는 tuple 모음

RDBMS 과 SQL 은 정규화된 구조로 데이터를 저장하고 질의할 필요가 있는 대부분이 선택하는 도구가 되었다 +
transaction, batch 처리

=== NoSQL 의 탄생

원래는 오픈소스, 분산 환경, non RBDMS meetup 용 트위터 해시태그

**Not Only SQL** 로 재해석

NoSQL DB 채택의 이유?

* 대규모 데이터셋, 매우 높은 쓰기 처리량 달성을 RDBMS 보다 쉽게 할 수 있는 확장성 필요
* 상용 DB 제품보다 무료 오픈소스 소프트웨어에 대한 선호
* 관게형 모델에서 지원하지 않는 특수 질의 동작
* 관게형 스키마 제한에 대한 불만, 동적이고 표현력이 풍부한 데이터 모델에 대한 바람

관계형, 비관계형을 함께 사용 - polyglot persistence

=== 객체 관계형 불일치

애플리케이션 코드 - DB 모델 객체 사이에 전환 계층이 필요하다 (impendance mismatch)

document-oriented DB 는 JSON 데이터 모델 지원 - MongoDB, RethinkDB, CouchDB, Espresso 등

=== many-to-one, many-to-many 관계

중복의 문제 +
의미 있는 정보는 한 곳에만 저장하고, 참조하는 모든 것은 ID 를 사용

중복 데이터 정규화 - many-to-one +
문서 모델에는 적합하지 않음. RDB 에서는 조인이 쉽지만 Document DB 에서는 조인이 약하다

DB 가 조인을 지원하지 않으면 다중 질의를 만들어서 애플리케이션 코드에서 조인을 흉내내야 한다

=== Document DB 는 역사를 반복하고 있나?

Document DB 와 NoSQL 에서 many-to-many 를 표현하는 제일 좋은 방법?

계층 모델: 간단, 모든 데이터를 레코드 내에 중첩된 레코드 트리로 표현, many-to-many join 이 안됨

계층 모델의 한계를 해결하기 위한 해결책들

==== 네트워크 모델

코다실 모델이라고도 함. 안쓰인다

계층 모델의 트리 구조에서 모든 레코드는 하나의 부모가 있는데, **네트워크 모델에서는 여러 개 가능**

FK 보다는 포인터와 비슷하다 +
레코드에 접근하는 방법은 접근 경로 - 최상위 레코드에서부터 연속된 연결 경로를 따르기

접근 경로를 따라 DB 끝에서 끝까지 커서를 움직여 수행 +
다중 부모인 경우 다양한 관계를 모두 추적해야 한다

제한된 하드웨어 성능을 효율적으로 사용할 수 있었지만 +
query, update 를 위한 코드가 복잡하고 유연하지 못한 문제

==== 관계형 모델

알려진 모든 데이터를 배치 +
관계 (테이블) = 튜플 (로우) 컬렉션

condition, all, one 읽기 +
다른 테이블 관계 없이 새 row insert 가능

query optimizer 가 query 의 어느 부분을 어떤 순서로 실행할지 결정, 사용할 index 를 자동으로 결정

==== Document DB 와의 비교

Document DB 는 계층 모델

many-to-one, many-to-many 은 RDB, Document DB 가 근본적으로는 다르지 않다 +
Unique ID 로 참조 (Foreign Key, document reference)

현재까지는 Document DB 가 코다실의 역사를 반복하진 않음

=== RDB 와 오늘날의 Document DB

데이터 모델의 차이점

Document DB - 스키마 유연성, 지역성 (더 나은 성능), 애플리케이션 데이터 구조와 가까움

==== 애플리케이션 코드를 더 간단하게 하는 데이터 모델?

데이터가 Document 와 비슷한 한 번에 전체 트리를 적재하는 구조 라면 Document 모델을 사용 +
여러 테이블로 나누어 찢는 (sherdding) 관계형 기법은 다루기 힘든 스키마, 불필요하게 복잡한 애플리케이션 코드 발생

Document 모델에서 중첩 항목은 바로 참조할 수 없다

비정규화로 조인을 줄일 수 있지만 비정규화된 데이터 일관성을 유지하기 위해 추가 작업을 해야 한다 +
Document 모델 사용하면서 애플리케이션 단에서 조인하는건 복잡한 코드, 나쁜 성능으로 이어질 수 있다

데이터 항목 간에 존재하는 관계 유형에 따라 데이터 모델을 선택

==== Document 모델에서 스키마 유연성

RDB, Document DB 에서 지원하는 JSON 은 스키마를 강요하지 않는다 +
= 임의 키/값을 추가할 수 있고 읽을 때 필드 존재 여부를 보장하지 않는다

애플리케이션에서 읽는 암묵적인 스키마가 있지만, Document DB 단에서는 강요하지 않는다

* schema-on-write: 명시적인 스키마, DB 는 스키마를 잘 따르고 있다
* schema-on-read: 암묵적인 스키마, 데이터를 읽을 때만 해석
** 데이터가 여러 다른 유형으로 구성되어 있을 때 유리

==== 질의를 위한 데이터 지역성

Document 는 JSON, XML 의 연속 문자열 or binary JSON, XML 로 저장

애플리케이션이 자주 전체 문서에 접근해야 할 때, 저장소 지역성 (storage locality) 을 활용한 성능 이점

(저장소 지역성???)

한 번에 문서의 많은 부분을 필요로 하는 경우에만 적용

Spanner, Oracle multi-table index cluster table, Bigtable column-family

==== Document DB 와 RDB 의 혼합

서로 부족한 부분을 보완해나가는 중이므로 해당 기능 사용

== 데이터를 위한 질의 언어

SQL - 선언형, 관계 대수 (relational algebra) 의 구조를 유사하게 따름 +
결과가 충족해야 하는 조건과 데이터를 어떻게 변환할지를 지정

* DB 엔진의 구현이 숨어있음 -> 쿼리를 변경하지 않고도 DB 시스템 성능 향상 가능
* DB 에게 자동으로 최적화할 수 있는 여지를 더 많이 준다
* 병렬 실행에 적합하다

=== 웹에서의 선언형 질의

CSS, XSL

=== 맵리듀스 질의

맵리듀스: 많은 컴퓨터에서 대량의 데이터를 처리하기 위한 프로그래밍 모델 +
일부 NoSQL 에서 제한된 형태로 지원

선언형과 명령형의 중간 정도 +
쿼리 로직은 프레임워크가 반복적으로 호출하는 조각 코드로 표현 +
map, reduce 함수를 기반으로 함

p47 - SQL 과 MapReduce 코드 예시

예시로 보면, js 함수 두 개를 신중하게 작성해야 하는 사용성 문제 +
-> MongoDB 에서는 aggregation pipeline 이라는 선언형 질의 언어 추가 (p49)

== 그래프형 데이터 모델

many-to-many 관계가 매우 일반적이라면? - 그래프로 데이터를 모델링하는게 자연스럽다

그래프의 구성

* vertex (node or entity)
* edge (relation or arc)
* 그래프 예시: 소셜 (사람 - 알고 있음), 웹 (웹 페이지 - 다른 페이지에 대한 링크), 도로/철도 (교차로 - 교차로 간 도로/철로 선)
* 실 예시: 내비게이션 (지점 간 최단 경로), pagerank (웹 그래프)

그래프에서 데이터를 구조화하고 질의하는 방법들

* 속성 그래프 모델 - Neo4j, Titan, InfiniteGraph 등
* 트리플 저장소 모델 - Datomic, Allegrograph 등

그래프용 선언헌 질의 언어 - Cypher, SPARQL, Datalog +
명령형 - Gremline +
그래프 처리 프레임워크 - Pregel

=== 속성 그래프

구성 요소들

* vertex: 고유한 식별자, outgoing/incoming edge 집합, 속성 컬렉션 (key-value pair)
* edge: 고유한 식별자, 시작/끝 edge (tail/head edge), 두 vertex 간 관계 유형을 설명하는 label, 속성 컬렉션 (key-value pair)

그래프는 데이터 모델링을 위한 많은 유연성을 제공한다 (프랑스는 주/도, 미국은 군/주 로 구분) +
애플리케이션에 기능을 추가하는 경우 애플리케이션의 데이터 구조 변경을 수용하게끔 그래프를 쉽게 확장할 수 있다

=== Cypher

속성 그래프를 위한 선언형 쿼리 언어 - Neo4j 그래프 DB 용으로 만들어졌다

쿼리의 다른 부분에 이름을 이용하여 vertex 간 edge 를 화살표 표기를 사용해 만들 수 있다 +
`(Idaho) -[:WITHIN]-> (USA)`: tail -label-> head

=== SQL 의 그래프 쿼리

그래프 데이터를 관계형 구조로 넣어도 SQL 로 쿼리할 수 있나? +
RDB 에서는 필요한 조인을 미리 알고 있어야 하는데, 그래프 질의는 가변적인 여러 edge 를 순회해야 한다

가변 순회 경로에 대한 질의 개념 - **recursive common table expression** (`WITH RECURSIVE`)

=== 트리플 저장소와 SPARQL

속성 그래프 모델과 거의 같다

모든 정보를 매우 간단한 three-part statements 형식으로 저장 +
(subject, predicate, object 와 같은 형태)

subject 는 그래프의 vertex 와 같음 +
object 는 두 가지 중 하나

. primitive datatype 의 값: subject vertex 에서 속성의 key, value 와 동등
** (루시, 나이, 33) = {"age":33}
. 그래프의 다른 vertex: predicate - edge, subject - tail vertex, object - head vertex
** (루시, 결혼하다, 알랭)

p57 Turtle 로 작성한 예시

==== 시맨틱 웹

트리플 저장소 데이터 모델은 시맨틱 웹과는 독립적이다

웹 사이트를 (컴퓨터가 읽게끔) 기계가 판독 가능한 데이터로도 정보를 게시하게 하는 개념

Resource Description Framework - 웹사이트가 일관된 형식으로 데이터를 게시하기 위한 방법 제안

==== RDF 데이터 모델

한 눈에 보기 쉽게 하기 위해 Turtle/Notation3 를 선호

RDF 에서의 주목보: URI (실제 접속 가능한 주소가 아니어도 됨, 단순 네임스페이스)

내부 cuve 와 비슷한듯..

==== SPARQL

SPARQL Protocol and RDF Query Language

RDF 데이터 모델을 사용한 트리플 저장소 질의 언어

.그래프 DB 와 네트워크 모델의 비교
****

코다실과 그래프 DB 가 다른 점

* 코다실 DB 에는 스키마가 있고, 그래프 DB 에서는 제한이 없다
* 코다실에서 특정 데이터를 도달하는 유일한 방법 - 레코드 접근 경로 중 하나를 탐색
** 그래프 DB 에서는 고유 ID 를 가짐, 인덱싱 가능
* 코다실은 데이터 정렬을 유지해야 함, 그래프 DB 는 질의를 만들 때만 결과를 정렬할 수 있음
* 코다실은 명령형이고 스키마가 변경되면 쿼리가 쉽게 손상, 그래프 DB 는 고수준의 선언형 질의 언어 제공

****

==== 초석 (The Foundation): Datalog

1980년대부터 연구된 언어 - 이후 질의 언어의 기반이 되는 초석 제공

트리플 저장소 모델과 유사 - **predicate(subject, object)**

datalog 는 prolog 의 부분 집합

datalog 는 단계를 나눠 조금씩 질의로 나아간다 (예제 2-11) +

* predicate 를 데이터나 다른 규칙에서 파생하여 사용할 수 있음
* 복잡한 질의를 작은 부분으로 나눠서 구성할 수 있음
* 대문자 = 변수

다른 질의의 규칙을 결합하거나 재사용할 수 있기 때문에 매우 강력하다 +
데이터가 복잡하면 더 효과적으로 대처할 수 있다